"use client";

import { 
  IconDashboard,
  IconUsers,
  IconShoppingBag,
  IconShoppingCart,
  IconChartBar,
  IconSettings,
  IconHome,
  IconCalendar,
  IconBuildingStore,
  IconReportAnalytics,
  IconUserCircle,
  IconDeviceAnalytics,
  IconShield,
  IconKey,
  IconFolder,
  IconTag,
  IconRefresh,
  IconCreditCard,
  IconChartLine,
  IconBox,
  IconMail,
  IconUserCheck,
  IconUserX,
  IconShieldCheck,
  IconServer,
  IconPuzzle,
  IconCircle,
  IconCircleX,
  IconFolderPlus,
  IconFolderMinus,
  IconCheck,
  IconActivity
} from '@tabler/icons-react';

export const iconMap: Record<string, React.ReactNode> = {
  dashboard: <IconDashboard size={20} stroke={1.5} />,
  home: <IconHome size={20} stroke={1.5} />,
  users: <IconUsers size={20} stroke={1.5} />,
  'shopping-bag': <IconShoppingBag size={20} stroke={1.5} />,
  'shopping-cart': <IconShoppingCart size={20} stroke={1.5} />,
  'chart-bar': <IconChartBar size={20} stroke={1.5} />,
  settings: <IconSettings size={20} stroke={1.5} />,
  calendar: <IconCalendar size={20} stroke={1.5} />,
  store: <IconBuildingStore size={20} stroke={1.5} />,
  reports: <IconReportAnalytics size={20} stroke={1.5} />,
  profile: <IconUserCircle size={20} stroke={1.5} />,
  analytics: <IconDeviceAnalytics size={20} stroke={1.5} />,
  shield: <IconShield size={20} stroke={1.5} />,
  key: <IconKey size={20} stroke={1.5} />,
  folder: <IconFolder size={20} stroke={1.5} />,
  tag: <IconTag size={20} stroke={1.5} />,
  refresh: <IconRefresh size={20} stroke={1.5} />,
  'credit-card': <IconCreditCard size={20} stroke={1.5} />,
  'chart-line': <IconChartLine size={20} stroke={1.5} />,
  box: <IconBox size={20} stroke={1.5} />,
  mail: <IconMail size={20} stroke={1.5} />,
  'user-check': <IconUserCheck size={20} stroke={1.5} />,
  'user-x': <IconUserX size={20} stroke={1.5} />,
  'shield-check': <IconShieldCheck size={20} stroke={1.5} />,
  server: <IconServer size={20} stroke={1.5} />,
  puzzle: <IconPuzzle size={20} stroke={1.5} />,
  'check-circle': <IconCircle size={20} stroke={1.5} />,
  'x-circle': <IconCircleX size={20} stroke={1.5} />,
  'folder-plus': <IconFolderPlus size={20} stroke={1.5} />,
  'folder-minus': <IconFolderMinus size={20} stroke={1.5} />,
  'tag-check': <IconCheck size={20} stroke={1.5} />,
  'tag-x': <IconTag size={20} stroke={1.5} />,
  'user-activity': <IconActivity size={20} stroke={1.5} />
}; 