//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateSysDictionaryDataRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public string Dictcode { get; set; }

        public long Id { get; set; }

        public string Label { get; set; }

        public long Modifyby { get; set; }

        public System.DateTime Modifytime { get; set; }

        public int Ordinal { get; set; }

        public bool Status { get; set; }

        public string Tagtype { get; set; }

        public string Value { get; set; }

        #endregion
    }
    public class UpdateSysDictionaryDataRequestValidator : CustomValidator<UpdateSysDictionaryDataRequest>
    {
       public UpdateSysDictionaryDataRequestValidator(IReadRepository<SysDictionaryData> repository, IStringLocalizer<UpdateSysDictionaryDataRequestValidator> localizer){}
    }
    public class UpdateSysDictionaryDataRequestHandler : IRequestHandler<UpdateSysDictionaryDataRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysDictionaryData> _repository;
    private readonly IStringLocalizer<UpdateSysDictionaryDataRequestHandler> _localizer;

    public UpdateSysDictionaryDataRequestHandler(IRepositoryWithEvents<SysDictionaryData> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateSysDictionaryDataRequest request, CancellationToken cancellationToken)
    {
        var sysDictionaryData = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysDictionaryData ?? throw new NotFoundException(string.Format(_localizer["sysDictionaryData.notfound"], request.Id));

        sysDictionaryData.Update(request.Createby,request.Createtime,request.Dictcode,request.Id,request.Label,request.Modifyby,request.Modifytime,request.Ordinal,request.Status,request.Tagtype,request.Value);

        await _repository.UpdateAsync(sysDictionaryData, cancellationToken);

        return request.Id;
    }
   }

}
