//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurAssignmentSubmissionsRequest : IRequest<Int64>
    {

        #region Properties

        public long AssignmentId { get; set; }

        public string Comment { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public string FileUrl { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public System.DateTime? ReviewedAt { get; set; }

        public long? ReviewedBy { get; set; }

        public decimal? Score { get; set; }

        public long StudentId { get; set; }

        public System.DateTime? SubmittedAt { get; set; }

        #endregion
    }
    public class UpdateCurAssignmentSubmissionsRequestValidator : CustomValidator<UpdateCurAssignmentSubmissionsRequest>
    {
       public UpdateCurAssignmentSubmissionsRequestValidator(IReadRepository<CurAssignmentSubmissions> repository, IStringLocalizer<UpdateCurAssignmentSubmissionsRequestValidator> localizer){}
    }
    public class UpdateCurAssignmentSubmissionsRequestHandler : IRequestHandler<UpdateCurAssignmentSubmissionsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurAssignmentSubmissions> _repository;
    private readonly IStringLocalizer<UpdateCurAssignmentSubmissionsRequestHandler> _localizer;

    public UpdateCurAssignmentSubmissionsRequestHandler(IRepositoryWithEvents<CurAssignmentSubmissions> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurAssignmentSubmissionsRequest request, CancellationToken cancellationToken)
    {
        var curAssignmentSubmissions = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curAssignmentSubmissions ?? throw new NotFoundException(string.Format(_localizer["curAssignmentSubmissions.notfound"], request.Id));

        curAssignmentSubmissions.Update(request.AssignmentId,request.Comment,request.Createby,request.Createtime,request.FileUrl,request.Id,request.Isdeleted,request.Modifyby,request.Modifytime,request.ReviewedAt,request.ReviewedBy,request.Score,request.StudentId,request.SubmittedAt);

        await _repository.UpdateAsync(curAssignmentSubmissions, cancellationToken);

        return request.Id;
    }
   }

}
