//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurAttendancesRequest : IRequest<Int64>
    {

        #region Properties

        public long ClassId { get; set; }

        public long Createby { get; set; }

        public System.DateTime? CreatedAt { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public System.DateTime SessionDate { get; set; }

        public string Status { get; set; }

        public long StudentId { get; set; }

        public System.DateTime? UpdatedAt { get; set; }

        #endregion
    }
    public class UpdateCurAttendancesRequestValidator : CustomValidator<UpdateCurAttendancesRequest>
    {
       public UpdateCurAttendancesRequestValidator(IReadRepository<CurAttendances> repository, IStringLocalizer<UpdateCurAttendancesRequestValidator> localizer){}
    }
    public class UpdateCurAttendancesRequestHandler : IRequestHandler<UpdateCurAttendancesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurAttendances> _repository;
    private readonly IStringLocalizer<UpdateCurAttendancesRequestHandler> _localizer;

    public UpdateCurAttendancesRequestHandler(IRepositoryWithEvents<CurAttendances> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurAttendancesRequest request, CancellationToken cancellationToken)
    {
        var curAttendances = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curAttendances ?? throw new NotFoundException(string.Format(_localizer["curAttendances.notfound"], request.Id));

        curAttendances.Update(request.ClassId,request.Createby,request.CreatedAt,request.Createtime,request.Id,request.Isdeleted,request.Modifyby,request.Modifytime,request.SessionDate,request.Status,request.StudentId,request.UpdatedAt);

        await _repository.UpdateAsync(curAttendances, cancellationToken);

        return request.Id;
    }
   }

}
