//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateSysUserTypeRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool IsDeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        #endregion
    }
    public class UpdateSysUserTypeRequestValidator : CustomValidator<UpdateSysUserTypeRequest>
    {
       public UpdateSysUserTypeRequestValidator(IReadRepository<SysUserType> repository, IStringLocalizer<UpdateSysUserTypeRequestValidator> localizer){}
    }
    public class UpdateSysUserTypeRequestHandler : IRequestHandler<UpdateSysUserTypeRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysUserType> _repository;
    private readonly IStringLocalizer<UpdateSysUserTypeRequestHandler> _localizer;

    public UpdateSysUserTypeRequestHandler(IRepositoryWithEvents<SysUserType> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateSysUserTypeRequest request, CancellationToken cancellationToken)
    {
        var sysUserType = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysUserType ?? throw new NotFoundException(string.Format(_localizer["sysUserType.notfound"], request.Id));

        sysUserType.Update(request.Createby,request.Createtime,request.Id,request.IsDeleted,request.Modifyby,request.Modifytime,request.Name);

        await _repository.UpdateAsync(sysUserType, cancellationToken);

        return request.Id;
    }
   }

}
