//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurSchedulesRequest : IRequest<Int64>
    {

        #region Properties

        public long ClassId { get; set; }

        public long Createby { get; set; }

        public System.DateTime? CreatedAt { get; set; }

        public System.DateTime Createtime { get; set; }

        public System.TimeSpan EndTime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public string Location { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public System.TimeSpan StartTime { get; set; }

        public System.DateTime? UpdatedAt { get; set; }

        public string Weekday { get; set; }

        #endregion
    }
    public class UpdateCurSchedulesRequestValidator : CustomValidator<UpdateCurSchedulesRequest>
    {
       public UpdateCurSchedulesRequestValidator(IReadRepository<CurSchedules> repository, IStringLocalizer<UpdateCurSchedulesRequestValidator> localizer){}
    }
    public class UpdateCurSchedulesRequestHandler : IRequestHandler<UpdateCurSchedulesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurSchedules> _repository;
    private readonly IStringLocalizer<UpdateCurSchedulesRequestHandler> _localizer;

    public UpdateCurSchedulesRequestHandler(IRepositoryWithEvents<CurSchedules> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurSchedulesRequest request, CancellationToken cancellationToken)
    {
        var curSchedules = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curSchedules ?? throw new NotFoundException(string.Format(_localizer["curSchedules.notfound"], request.Id));

        curSchedules.Update(request.ClassId,request.Createby,request.CreatedAt,request.Createtime,request.EndTime,request.Id,request.Isdeleted,request.Location,request.Modifyby,request.Modifytime,request.StartTime,request.UpdatedAt,request.Weekday);

        await _repository.UpdateAsync(curSchedules, cancellationToken);

        return request.Id;
    }
   }

}
