//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurDenominationsRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public int Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        #endregion
    }
    public class UpdateCurDenominationsRequestValidator : CustomValidator<UpdateCurDenominationsRequest>
    {
       public UpdateCurDenominationsRequestValidator(IReadRepository<CurDenominations> repository, IStringLocalizer<UpdateCurDenominationsRequestValidator> localizer){}
    }
    public class UpdateCurDenominationsRequestHandler : IRequestHandler<UpdateCurDenominationsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurDenominations> _repository;
    private readonly IStringLocalizer<UpdateCurDenominationsRequestHandler> _localizer;

    public UpdateCurDenominationsRequestHandler(IRepositoryWithEvents<CurDenominations> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurDenominationsRequest request, CancellationToken cancellationToken)
    {
        var curDenominations = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curDenominations ?? throw new NotFoundException(string.Format(_localizer["curDenominations.notfound"], request.Id));

        curDenominations.Update(request.Createby,request.Createtime,request.Id,request.Isdeleted,request.Modifyby,request.Modifytime,request.Name);

        await _repository.UpdateAsync(curDenominations, cancellationToken);

        return request.Id;
    }
   }

}
