//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurDegreesRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public int Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        #endregion
    }
    public class UpdateCurDegreesRequestValidator : CustomValidator<UpdateCurDegreesRequest>
    {
       public UpdateCurDegreesRequestValidator(IReadRepository<CurDegrees> repository, IStringLocalizer<UpdateCurDegreesRequestValidator> localizer){}
    }
    public class UpdateCurDegreesRequestHandler : IRequestHandler<UpdateCurDegreesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurDegrees> _repository;
    private readonly IStringLocalizer<UpdateCurDegreesRequestHandler> _localizer;

    public UpdateCurDegreesRequestHandler(IRepositoryWithEvents<CurDegrees> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurDegreesRequest request, CancellationToken cancellationToken)
    {
        var curDegrees = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curDegrees ?? throw new NotFoundException(string.Format(_localizer["curDegrees.notfound"], request.Id));

        curDegrees.Update(request.Createby,request.Createtime,request.Id,request.Isdeleted,request.Modifyby,request.Modifytime,request.Name);

        await _repository.UpdateAsync(curDegrees, cancellationToken);

        return request.Id;
    }
   }

}
