//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateSysConfigRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public string Key { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        public string Remark { get; set; }

        public string Value { get; set; }

        #endregion
    }
    public class UpdateSysConfigRequestValidator : CustomValidator<UpdateSysConfigRequest>
    {
       public UpdateSysConfigRequestValidator(IReadRepository<SysConfig> repository, IStringLocalizer<UpdateSysConfigRequestValidator> localizer){}
    }
    public class UpdateSysConfigRequestHandler : IRequestHandler<UpdateSysConfigRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysConfig> _repository;
    private readonly IStringLocalizer<UpdateSysConfigRequestHandler> _localizer;

    public UpdateSysConfigRequestHandler(IRepositoryWithEvents<SysConfig> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateSysConfigRequest request, CancellationToken cancellationToken)
    {
        var sysConfig = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysConfig ?? throw new NotFoundException(string.Format(_localizer["sysConfig.notfound"], request.Id));

        sysConfig.Update(request.Createby,request.Createtime,request.Id,request.Key,request.Modifyby,request.Modifytime,request.Name,request.Remark,request.Value);

        await _repository.UpdateAsync(sysConfig, cancellationToken);

        return request.Id;
    }
   }

}
