//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurQuestionAnswersRequest : IRequest<Int64>
    {

        #region Properties

        public string AnswerText { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public long QuestionId { get; set; }

        public decimal? Score { get; set; }

        public string SelectedOptionIds { get; set; }

        public long SubmissionId { get; set; }

        #endregion
    }
    public class UpdateCurQuestionAnswersRequestValidator : CustomValidator<UpdateCurQuestionAnswersRequest>
    {
       public UpdateCurQuestionAnswersRequestValidator(IReadRepository<CurQuestionAnswers> repository, IStringLocalizer<UpdateCurQuestionAnswersRequestValidator> localizer){}
    }
    public class UpdateCurQuestionAnswersRequestHandler : IRequestHandler<UpdateCurQuestionAnswersRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurQuestionAnswers> _repository;
    private readonly IStringLocalizer<UpdateCurQuestionAnswersRequestHandler> _localizer;

    public UpdateCurQuestionAnswersRequestHandler(IRepositoryWithEvents<CurQuestionAnswers> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurQuestionAnswersRequest request, CancellationToken cancellationToken)
    {
        var curQuestionAnswers = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curQuestionAnswers ?? throw new NotFoundException(string.Format(_localizer["curQuestionAnswers.notfound"], request.Id));

        curQuestionAnswers.Update(request.AnswerText,request.Createby,request.Createtime,request.Id,request.Isdeleted,request.Modifyby,request.Modifytime,request.QuestionId,request.Score,request.SelectedOptionIds,request.SubmissionId);

        await _repository.UpdateAsync(curQuestionAnswers, cancellationToken);

        return request.Id;
    }
   }

}
