//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurCourseContentsRequest : IRequest<Int64>
    {

        #region Properties

        public string ContentDescription { get; set; }

        public int? CourseId { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        #endregion
    }
    public class UpdateCurCourseContentsRequestValidator : CustomValidator<UpdateCurCourseContentsRequest>
    {
       public UpdateCurCourseContentsRequestValidator(IReadRepository<CurCourseContents> repository, IStringLocalizer<UpdateCurCourseContentsRequestValidator> localizer){}
    }
    public class UpdateCurCourseContentsRequestHandler : IRequestHandler<UpdateCurCourseContentsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurCourseContents> _repository;
    private readonly IStringLocalizer<UpdateCurCourseContentsRequestHandler> _localizer;

    public UpdateCurCourseContentsRequestHandler(IRepositoryWithEvents<CurCourseContents> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurCourseContentsRequest request, CancellationToken cancellationToken)
    {
        var curCourseContents = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curCourseContents ?? throw new NotFoundException(string.Format(_localizer["curCourseContents.notfound"], request.Id));

        curCourseContents.Update(request.ContentDescription,request.CourseId,request.Createby,request.Createtime,request.Id,request.Isdeleted,request.Modifyby,request.Modifytime);

        await _repository.UpdateAsync(curCourseContents, cancellationToken);

        return request.Id;
    }
   }

}
