//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurQuizzesRequest : IRequest<Int64>
    {

        #region Properties

        public long ClassId { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public string Description { get; set; }

        public int? DurationMinutes { get; set; }

        public System.DateTime? EndTime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public System.DateTime? StartTime { get; set; }

        public string Title { get; set; }

        public int? TotalScore { get; set; }

        #endregion
    }
    public class UpdateCurQuizzesRequestValidator : CustomValidator<UpdateCurQuizzesRequest>
    {
       public UpdateCurQuizzesRequestValidator(IReadRepository<CurQuizzes> repository, IStringLocalizer<UpdateCurQuizzesRequestValidator> localizer){}
    }
    public class UpdateCurQuizzesRequestHandler : IRequestHandler<UpdateCurQuizzesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurQuizzes> _repository;
    private readonly IStringLocalizer<UpdateCurQuizzesRequestHandler> _localizer;

    public UpdateCurQuizzesRequestHandler(IRepositoryWithEvents<CurQuizzes> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurQuizzesRequest request, CancellationToken cancellationToken)
    {
        var curQuizzes = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curQuizzes ?? throw new NotFoundException(string.Format(_localizer["curQuizzes.notfound"], request.Id));

        curQuizzes.Update(request.ClassId,request.Createby,request.Createtime,request.Description,request.DurationMinutes,request.EndTime,request.Id,request.Isdeleted,request.Modifyby,request.Modifytime,request.StartTime,request.Title,request.TotalScore);

        await _repository.UpdateAsync(curQuizzes, cancellationToken);

        return request.Id;
    }
   }

}
