//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurClassesRequest : IRequest<Int64>
    {

        #region Properties

        public long CourseId { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public System.DateTime? EndDate { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public int? MaxStudents { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public System.DateTime? StartDate { get; set; }

        public string Status { get; set; }

        public long TeacherId { get; set; }

        #endregion
    }
    public class UpdateCurClassesRequestValidator : CustomValidator<UpdateCurClassesRequest>
    {
       public UpdateCurClassesRequestValidator(IReadRepository<CurClasses> repository, IStringLocalizer<UpdateCurClassesRequestValidator> localizer){}
    }
    public class UpdateCurClassesRequestHandler : IRequestHandler<UpdateCurClassesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurClasses> _repository;
    private readonly IStringLocalizer<UpdateCurClassesRequestHandler> _localizer;

    public UpdateCurClassesRequestHandler(IRepositoryWithEvents<CurClasses> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurClassesRequest request, CancellationToken cancellationToken)
    {
        var curClasses = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curClasses ?? throw new NotFoundException(string.Format(_localizer["curClasses.notfound"], request.Id));

        curClasses.Update(request.CourseId,request.Createby,request.Createtime,request.EndDate,request.Id,request.Isdeleted,request.MaxStudents,request.Modifyby,request.Modifytime,request.StartDate,request.Status,request.TeacherId);

        await _repository.UpdateAsync(curClasses, cancellationToken);

        return request.Id;
    }
   }

}
