//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateSysRoleRequest : IRequest<Int64>
    {

        #region Properties

        public string Code { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public int Datascope { get; set; }

        public string FkMenu { get; set; }

        public long Id { get; set; }

        public long Modifyby { get; set; }

        public System.DateTime Modifytime { get; set; }

        public string Name { get; set; }

        public int Ordinal { get; set; }

        public bool Status { get; set; }

        #endregion
    }
    public class UpdateSysRoleRequestValidator : CustomValidator<UpdateSysRoleRequest>
    {
       public UpdateSysRoleRequestValidator(IReadRepository<SysRole> repository, IStringLocalizer<UpdateSysRoleRequestValidator> localizer){}
    }
    public class UpdateSysRoleRequestHandler : IRequestHandler<UpdateSysRoleRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysRole> _repository;
    private readonly IStringLocalizer<UpdateSysRoleRequestHandler> _localizer;

    public UpdateSysRoleRequestHandler(IRepositoryWithEvents<SysRole> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateSysRoleRequest request, CancellationToken cancellationToken)
    {
        var sysRole = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysRole ?? throw new NotFoundException(string.Format(_localizer["sysRole.notfound"], request.Id));

        sysRole.Update(request.Code,request.Createby,request.Createtime,request.Datascope,request.FkMenu,request.Id,request.Modifyby,request.Modifytime,request.Name,request.Ordinal,request.Status);

        await _repository.UpdateAsync(sysRole, cancellationToken);

        return request.Id;
    }
   }

}
