//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurQualificationsRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string QualificationLevel { get; set; }

        #endregion
    }
    public class UpdateCurQualificationsRequestValidator : CustomValidator<UpdateCurQualificationsRequest>
    {
       public UpdateCurQualificationsRequestValidator(IReadRepository<CurQualifications> repository, IStringLocalizer<UpdateCurQualificationsRequestValidator> localizer){}
    }
    public class UpdateCurQualificationsRequestHandler : IRequestHandler<UpdateCurQualificationsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurQualifications> _repository;
    private readonly IStringLocalizer<UpdateCurQualificationsRequestHandler> _localizer;

    public UpdateCurQualificationsRequestHandler(IRepositoryWithEvents<CurQualifications> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurQualificationsRequest request, CancellationToken cancellationToken)
    {
        var curQualifications = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curQualifications ?? throw new NotFoundException(string.Format(_localizer["curQualifications.notfound"], request.Id));

        curQualifications.Update(request.Createby,request.Createtime,request.Id,request.Isdeleted,request.Modifyby,request.Modifytime,request.QualificationLevel);

        await _repository.UpdateAsync(curQualifications, cancellationToken);

        return request.Id;
    }
   }

}
