//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurCourseTypesRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        #endregion
    }
    public class UpdateCurCourseTypesRequestValidator : CustomValidator<UpdateCurCourseTypesRequest>
    {
       public UpdateCurCourseTypesRequestValidator(IReadRepository<CurCourseTypes> repository, IStringLocalizer<UpdateCurCourseTypesRequestValidator> localizer){}
    }
    public class UpdateCurCourseTypesRequestHandler : IRequestHandler<UpdateCurCourseTypesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurCourseTypes> _repository;
    private readonly IStringLocalizer<UpdateCurCourseTypesRequestHandler> _localizer;

    public UpdateCurCourseTypesRequestHandler(IRepositoryWithEvents<CurCourseTypes> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurCourseTypesRequest request, CancellationToken cancellationToken)
    {
        var curCourseTypes = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curCourseTypes ?? throw new NotFoundException(string.Format(_localizer["curCourseTypes.notfound"], request.Id));

        curCourseTypes.Update(request.Createby,request.Createtime,request.Id,request.Isdeleted,request.Modifyby,request.Modifytime,request.Name);

        await _repository.UpdateAsync(curCourseTypes, cancellationToken);

        return request.Id;
    }
   }

}
