//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurSpecializationsRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        #endregion
    }
    public class UpdateCurSpecializationsRequestValidator : CustomValidator<UpdateCurSpecializationsRequest>
    {
       public UpdateCurSpecializationsRequestValidator(IReadRepository<CurSpecializations> repository, IStringLocalizer<UpdateCurSpecializationsRequestValidator> localizer){}
    }
    public class UpdateCurSpecializationsRequestHandler : IRequestHandler<UpdateCurSpecializationsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurSpecializations> _repository;
    private readonly IStringLocalizer<UpdateCurSpecializationsRequestHandler> _localizer;

    public UpdateCurSpecializationsRequestHandler(IRepositoryWithEvents<CurSpecializations> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurSpecializationsRequest request, CancellationToken cancellationToken)
    {
        var curSpecializations = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curSpecializations ?? throw new NotFoundException(string.Format(_localizer["curSpecializations.notfound"], request.Id));

        curSpecializations.Update(request.Createby,request.Createtime,request.Id,request.Isdeleted,request.Modifyby,request.Modifytime,request.Name);

        await _repository.UpdateAsync(curSpecializations, cancellationToken);

        return request.Id;
    }
   }

}
