//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateSysRoleUserRelationRequest : IRequest<Int64>
    {

        #region Properties

        public long Id { get; set; }

        public long Roleid { get; set; }

        public long Userid { get; set; }

        #endregion
    }
    public class UpdateSysRoleUserRelationRequestValidator : CustomValidator<UpdateSysRoleUserRelationRequest>
    {
       public UpdateSysRoleUserRelationRequestValidator(IReadRepository<SysRoleUserRelation> repository, IStringLocalizer<UpdateSysRoleUserRelationRequestValidator> localizer){}
    }
    public class UpdateSysRoleUserRelationRequestHandler : IRequestHandler<UpdateSysRoleUserRelationRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysRoleUserRelation> _repository;
    private readonly IStringLocalizer<UpdateSysRoleUserRelationRequestHandler> _localizer;

    public UpdateSysRoleUserRelationRequestHandler(IRepositoryWithEvents<SysRoleUserRelation> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateSysRoleUserRelationRequest request, CancellationToken cancellationToken)
    {
        var sysRoleUserRelation = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysRoleUserRelation ?? throw new NotFoundException(string.Format(_localizer["sysRoleUserRelation.notfound"], request.Id));

        sysRoleUserRelation.Update(request.Id,request.Roleid,request.Userid);

        await _repository.UpdateAsync(sysRoleUserRelation, cancellationToken);

        return request.Id;
    }
   }

}
