//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurOrganizationsRequest : IRequest<Int64>
    {

        #region Properties

        public string Code { get; set; }

        public long Createby { get; set; }

        public System.DateTime? CreatedAt { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public int? Level { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        public long? ParentId { get; set; }

        public string Path { get; set; }

        public string Type { get; set; }

        public System.DateTime? UpdatedAt { get; set; }

        #endregion
    }
    public class UpdateCurOrganizationsRequestValidator : CustomValidator<UpdateCurOrganizationsRequest>
    {
       public UpdateCurOrganizationsRequestValidator(IReadRepository<CurOrganizations> repository, IStringLocalizer<UpdateCurOrganizationsRequestValidator> localizer){}
    }
    public class UpdateCurOrganizationsRequestHandler : IRequestHandler<UpdateCurOrganizationsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurOrganizations> _repository;
    private readonly IStringLocalizer<UpdateCurOrganizationsRequestHandler> _localizer;

    public UpdateCurOrganizationsRequestHandler(IRepositoryWithEvents<CurOrganizations> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurOrganizationsRequest request, CancellationToken cancellationToken)
    {
        var curOrganizations = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curOrganizations ?? throw new NotFoundException(string.Format(_localizer["curOrganizations.notfound"], request.Id));

        curOrganizations.Update(request.Code,request.Createby,request.CreatedAt,request.Createtime,request.Id,request.Isdeleted,request.Level,request.Modifyby,request.Modifytime,request.Name,request.ParentId,request.Path,request.Type,request.UpdatedAt);

        await _repository.UpdateAsync(curOrganizations, cancellationToken);

        return request.Id;
    }
   }

}
