//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurQuizSubmissionsRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public long QuizId { get; set; }

        public long StudentId { get; set; }

        public System.DateTime? SubmittedAt { get; set; }

        public decimal? TotalScore { get; set; }

        #endregion
    }
    public class UpdateCurQuizSubmissionsRequestValidator : CustomValidator<UpdateCurQuizSubmissionsRequest>
    {
       public UpdateCurQuizSubmissionsRequestValidator(IReadRepository<CurQuizSubmissions> repository, IStringLocalizer<UpdateCurQuizSubmissionsRequestValidator> localizer){}
    }
    public class UpdateCurQuizSubmissionsRequestHandler : IRequestHandler<UpdateCurQuizSubmissionsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurQuizSubmissions> _repository;
    private readonly IStringLocalizer<UpdateCurQuizSubmissionsRequestHandler> _localizer;

    public UpdateCurQuizSubmissionsRequestHandler(IRepositoryWithEvents<CurQuizSubmissions> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurQuizSubmissionsRequest request, CancellationToken cancellationToken)
    {
        var curQuizSubmissions = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curQuizSubmissions ?? throw new NotFoundException(string.Format(_localizer["curQuizSubmissions.notfound"], request.Id));

        curQuizSubmissions.Update(request.Createby,request.Createtime,request.Id,request.Isdeleted,request.Modifyby,request.Modifytime,request.QuizId,request.StudentId,request.SubmittedAt,request.TotalScore);

        await _repository.UpdateAsync(curQuizSubmissions, cancellationToken);

        return request.Id;
    }
   }

}
