//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurCourseStandardsRequest : IRequest<Int64>
    {

        #region Properties

        public int? CourseId { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string StandardDescription { get; set; }

        #endregion
    }
    public class UpdateCurCourseStandardsRequestValidator : CustomValidator<UpdateCurCourseStandardsRequest>
    {
       public UpdateCurCourseStandardsRequestValidator(IReadRepository<CurCourseStandards> repository, IStringLocalizer<UpdateCurCourseStandardsRequestValidator> localizer){}
    }
    public class UpdateCurCourseStandardsRequestHandler : IRequestHandler<UpdateCurCourseStandardsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurCourseStandards> _repository;
    private readonly IStringLocalizer<UpdateCurCourseStandardsRequestHandler> _localizer;

    public UpdateCurCourseStandardsRequestHandler(IRepositoryWithEvents<CurCourseStandards> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurCourseStandardsRequest request, CancellationToken cancellationToken)
    {
        var curCourseStandards = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curCourseStandards ?? throw new NotFoundException(string.Format(_localizer["curCourseStandards.notfound"], request.Id));

        curCourseStandards.Update(request.CourseId,request.Createby,request.Createtime,request.Id,request.Isdeleted,request.Modifyby,request.Modifytime,request.StandardDescription);

        await _repository.UpdateAsync(curCourseStandards, cancellationToken);

        return request.Id;
    }
   }

}
