//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.update
{

    public class UpdateCurQuestionsRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public long QuizId { get; set; }

        public int? Score { get; set; }

        public string Text { get; set; }

        public string Type { get; set; }

        #endregion
    }
    public class UpdateCurQuestionsRequestValidator : CustomValidator<UpdateCurQuestionsRequest>
    {
       public UpdateCurQuestionsRequestValidator(IReadRepository<CurQuestions> repository, IStringLocalizer<UpdateCurQuestionsRequestValidator> localizer){}
    }
    public class UpdateCurQuestionsRequestHandler : IRequestHandler<UpdateCurQuestionsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurQuestions> _repository;
    private readonly IStringLocalizer<UpdateCurQuestionsRequestHandler> _localizer;

    public UpdateCurQuestionsRequestHandler(IRepositoryWithEvents<CurQuestions> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(UpdateCurQuestionsRequest request, CancellationToken cancellationToken)
    {
        var curQuestions = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curQuestions ?? throw new NotFoundException(string.Format(_localizer["curQuestions.notfound"], request.Id));

        curQuestions.Update(request.Createby,request.Createtime,request.Id,request.Isdeleted,request.Modifyby,request.Modifytime,request.QuizId,request.Score,request.Text,request.Type);

        await _repository.UpdateAsync(curQuestions, cancellationToken);

        return request.Id;
    }
   }

}
