//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteSysConfigRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteSysConfigRequestValidator : CustomValidator<DeleteSysConfigRequest>
    {
       public DeleteSysConfigRequestValidator(IReadRepository<SysConfig> repository, IStringLocalizer<DeleteSysConfigRequestValidator> localizer){}
    }
    public class DeleteSysConfigRequestHandler : IRequestHandler<DeleteSysConfigRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysConfig> _repository;
    private readonly IStringLocalizer<DeleteSysConfigRequestHandler> _localizer;

    public DeleteSysConfigRequestHandler(IRepositoryWithEvents<SysConfig> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteSysConfigRequest request, CancellationToken cancellationToken)
    {
        var sysConfig = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysConfig ?? throw new NotFoundException(_localizer["sysConfig.notfound"]);

        await _repository.DeleteAsync(sysConfig, cancellationToken);

        return request.Id;
    }
   }

}
