//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurSpecializationsRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurSpecializationsRequestValidator : CustomValidator<DeleteCurSpecializationsRequest>
    {
       public DeleteCurSpecializationsRequestValidator(IReadRepository<CurSpecializations> repository, IStringLocalizer<DeleteCurSpecializationsRequestValidator> localizer){}
    }
    public class DeleteCurSpecializationsRequestHandler : IRequestHandler<DeleteCurSpecializationsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurSpecializations> _repository;
    private readonly IStringLocalizer<DeleteCurSpecializationsRequestHandler> _localizer;

    public DeleteCurSpecializationsRequestHandler(IRepositoryWithEvents<CurSpecializations> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurSpecializationsRequest request, CancellationToken cancellationToken)
    {
        var curSpecializations = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curSpecializations ?? throw new NotFoundException(_localizer["curSpecializations.notfound"]);

        await _repository.DeleteAsync(curSpecializations, cancellationToken);

        return request.Id;
    }
   }

}
