//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurReligionsRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurReligionsRequestValidator : CustomValidator<DeleteCurReligionsRequest>
    {
       public DeleteCurReligionsRequestValidator(IReadRepository<CurReligions> repository, IStringLocalizer<DeleteCurReligionsRequestValidator> localizer){}
    }
    public class DeleteCurReligionsRequestHandler : IRequestHandler<DeleteCurReligionsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurReligions> _repository;
    private readonly IStringLocalizer<DeleteCurReligionsRequestHandler> _localizer;

    public DeleteCurReligionsRequestHandler(IRepositoryWithEvents<CurReligions> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurReligionsRequest request, CancellationToken cancellationToken)
    {
        var curReligions = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curReligions ?? throw new NotFoundException(_localizer["curReligions.notfound"]);

        await _repository.DeleteAsync(curReligions, cancellationToken);

        return request.Id;
    }
   }

}
