//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurQuizSubmissionsRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurQuizSubmissionsRequestValidator : CustomValidator<DeleteCurQuizSubmissionsRequest>
    {
       public DeleteCurQuizSubmissionsRequestValidator(IReadRepository<CurQuizSubmissions> repository, IStringLocalizer<DeleteCurQuizSubmissionsRequestValidator> localizer){}
    }
    public class DeleteCurQuizSubmissionsRequestHandler : IRequestHandler<DeleteCurQuizSubmissionsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurQuizSubmissions> _repository;
    private readonly IStringLocalizer<DeleteCurQuizSubmissionsRequestHandler> _localizer;

    public DeleteCurQuizSubmissionsRequestHandler(IRepositoryWithEvents<CurQuizSubmissions> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurQuizSubmissionsRequest request, CancellationToken cancellationToken)
    {
        var curQuizSubmissions = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curQuizSubmissions ?? throw new NotFoundException(_localizer["curQuizSubmissions.notfound"]);

        await _repository.DeleteAsync(curQuizSubmissions, cancellationToken);

        return request.Id;
    }
   }

}
