//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurCourseTypesRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurCourseTypesRequestValidator : CustomValidator<DeleteCurCourseTypesRequest>
    {
       public DeleteCurCourseTypesRequestValidator(IReadRepository<CurCourseTypes> repository, IStringLocalizer<DeleteCurCourseTypesRequestValidator> localizer){}
    }
    public class DeleteCurCourseTypesRequestHandler : IRequestHandler<DeleteCurCourseTypesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurCourseTypes> _repository;
    private readonly IStringLocalizer<DeleteCurCourseTypesRequestHandler> _localizer;

    public DeleteCurCourseTypesRequestHandler(IRepositoryWithEvents<CurCourseTypes> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurCourseTypesRequest request, CancellationToken cancellationToken)
    {
        var curCourseTypes = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curCourseTypes ?? throw new NotFoundException(_localizer["curCourseTypes.notfound"]);

        await _repository.DeleteAsync(curCourseTypes, cancellationToken);

        return request.Id;
    }
   }

}
