//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteSysRoleRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteSysRoleRequestValidator : CustomValidator<DeleteSysRoleRequest>
    {
       public DeleteSysRoleRequestValidator(IReadRepository<SysRole> repository, IStringLocalizer<DeleteSysRoleRequestValidator> localizer){}
    }
    public class DeleteSysRoleRequestHandler : IRequestHandler<DeleteSysRoleRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysRole> _repository;
    private readonly IStringLocalizer<DeleteSysRoleRequestHandler> _localizer;

    public DeleteSysRoleRequestHandler(IRepositoryWithEvents<SysRole> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteSysRoleRequest request, CancellationToken cancellationToken)
    {
        var sysRole = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysRole ?? throw new NotFoundException(_localizer["sysRole.notfound"]);

        await _repository.DeleteAsync(sysRole, cancellationToken);

        return request.Id;
    }
   }

}
