//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurAttendancesRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurAttendancesRequestValidator : CustomValidator<DeleteCurAttendancesRequest>
    {
       public DeleteCurAttendancesRequestValidator(IReadRepository<CurAttendances> repository, IStringLocalizer<DeleteCurAttendancesRequestValidator> localizer){}
    }
    public class DeleteCurAttendancesRequestHandler : IRequestHandler<DeleteCurAttendancesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurAttendances> _repository;
    private readonly IStringLocalizer<DeleteCurAttendancesRequestHandler> _localizer;

    public DeleteCurAttendancesRequestHandler(IRepositoryWithEvents<CurAttendances> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurAttendancesRequest request, CancellationToken cancellationToken)
    {
        var curAttendances = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curAttendances ?? throw new NotFoundException(_localizer["curAttendances.notfound"]);

        await _repository.DeleteAsync(curAttendances, cancellationToken);

        return request.Id;
    }
   }

}
