//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurAssignmentSubmissionsRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurAssignmentSubmissionsRequestValidator : CustomValidator<DeleteCurAssignmentSubmissionsRequest>
    {
       public DeleteCurAssignmentSubmissionsRequestValidator(IReadRepository<CurAssignmentSubmissions> repository, IStringLocalizer<DeleteCurAssignmentSubmissionsRequestValidator> localizer){}
    }
    public class DeleteCurAssignmentSubmissionsRequestHandler : IRequestHandler<DeleteCurAssignmentSubmissionsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurAssignmentSubmissions> _repository;
    private readonly IStringLocalizer<DeleteCurAssignmentSubmissionsRequestHandler> _localizer;

    public DeleteCurAssignmentSubmissionsRequestHandler(IRepositoryWithEvents<CurAssignmentSubmissions> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurAssignmentSubmissionsRequest request, CancellationToken cancellationToken)
    {
        var curAssignmentSubmissions = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curAssignmentSubmissions ?? throw new NotFoundException(_localizer["curAssignmentSubmissions.notfound"]);

        await _repository.DeleteAsync(curAssignmentSubmissions, cancellationToken);

        return request.Id;
    }
   }

}
