//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurCoursesRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurCoursesRequestValidator : CustomValidator<DeleteCurCoursesRequest>
    {
       public DeleteCurCoursesRequestValidator(IReadRepository<CurCourses> repository, IStringLocalizer<DeleteCurCoursesRequestValidator> localizer){}
    }
    public class DeleteCurCoursesRequestHandler : IRequestHandler<DeleteCurCoursesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurCourses> _repository;
    private readonly IStringLocalizer<DeleteCurCoursesRequestHandler> _localizer;

    public DeleteCurCoursesRequestHandler(IRepositoryWithEvents<CurCourses> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurCoursesRequest request, CancellationToken cancellationToken)
    {
        var curCourses = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curCourses ?? throw new NotFoundException(_localizer["curCourses.notfound"]);

        await _repository.DeleteAsync(curCourses, cancellationToken);

        return request.Id;
    }
   }

}
