//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurAssignmentsRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurAssignmentsRequestValidator : CustomValidator<DeleteCurAssignmentsRequest>
    {
       public DeleteCurAssignmentsRequestValidator(IReadRepository<CurAssignments> repository, IStringLocalizer<DeleteCurAssignmentsRequestValidator> localizer){}
    }
    public class DeleteCurAssignmentsRequestHandler : IRequestHandler<DeleteCurAssignmentsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurAssignments> _repository;
    private readonly IStringLocalizer<DeleteCurAssignmentsRequestHandler> _localizer;

    public DeleteCurAssignmentsRequestHandler(IRepositoryWithEvents<CurAssignments> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurAssignmentsRequest request, CancellationToken cancellationToken)
    {
        var curAssignments = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curAssignments ?? throw new NotFoundException(_localizer["curAssignments.notfound"]);

        await _repository.DeleteAsync(curAssignments, cancellationToken);

        return request.Id;
    }
   }

}
