//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurFieldsOfStudyRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurFieldsOfStudyRequestValidator : CustomValidator<DeleteCurFieldsOfStudyRequest>
    {
       public DeleteCurFieldsOfStudyRequestValidator(IReadRepository<CurFieldsOfStudy> repository, IStringLocalizer<DeleteCurFieldsOfStudyRequestValidator> localizer){}
    }
    public class DeleteCurFieldsOfStudyRequestHandler : IRequestHandler<DeleteCurFieldsOfStudyRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurFieldsOfStudy> _repository;
    private readonly IStringLocalizer<DeleteCurFieldsOfStudyRequestHandler> _localizer;

    public DeleteCurFieldsOfStudyRequestHandler(IRepositoryWithEvents<CurFieldsOfStudy> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurFieldsOfStudyRequest request, CancellationToken cancellationToken)
    {
        var curFieldsOfStudy = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curFieldsOfStudy ?? throw new NotFoundException(_localizer["curFieldsOfStudy.notfound"]);

        await _repository.DeleteAsync(curFieldsOfStudy, cancellationToken);

        return request.Id;
    }
   }

}
