//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurSchedulesRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurSchedulesRequestValidator : CustomValidator<DeleteCurSchedulesRequest>
    {
       public DeleteCurSchedulesRequestValidator(IReadRepository<CurSchedules> repository, IStringLocalizer<DeleteCurSchedulesRequestValidator> localizer){}
    }
    public class DeleteCurSchedulesRequestHandler : IRequestHandler<DeleteCurSchedulesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurSchedules> _repository;
    private readonly IStringLocalizer<DeleteCurSchedulesRequestHandler> _localizer;

    public DeleteCurSchedulesRequestHandler(IRepositoryWithEvents<CurSchedules> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurSchedulesRequest request, CancellationToken cancellationToken)
    {
        var curSchedules = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curSchedules ?? throw new NotFoundException(_localizer["curSchedules.notfound"]);

        await _repository.DeleteAsync(curSchedules, cancellationToken);

        return request.Id;
    }
   }

}
