//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteSysDictionaryRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteSysDictionaryRequestValidator : CustomValidator<DeleteSysDictionaryRequest>
    {
       public DeleteSysDictionaryRequestValidator(IReadRepository<SysDictionary> repository, IStringLocalizer<DeleteSysDictionaryRequestValidator> localizer){}
    }
    public class DeleteSysDictionaryRequestHandler : IRequestHandler<DeleteSysDictionaryRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysDictionary> _repository;
    private readonly IStringLocalizer<DeleteSysDictionaryRequestHandler> _localizer;

    public DeleteSysDictionaryRequestHandler(IRepositoryWithEvents<SysDictionary> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteSysDictionaryRequest request, CancellationToken cancellationToken)
    {
        var sysDictionary = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysDictionary ?? throw new NotFoundException(_localizer["sysDictionary.notfound"]);

        await _repository.DeleteAsync(sysDictionary, cancellationToken);

        return request.Id;
    }
   }

}
