//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteSysMenuRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteSysMenuRequestValidator : CustomValidator<DeleteSysMenuRequest>
    {
       public DeleteSysMenuRequestValidator(IReadRepository<SysMenu> repository, IStringLocalizer<DeleteSysMenuRequestValidator> localizer){}
    }
    public class DeleteSysMenuRequestHandler : IRequestHandler<DeleteSysMenuRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysMenu> _repository;
    private readonly IStringLocalizer<DeleteSysMenuRequestHandler> _localizer;

    public DeleteSysMenuRequestHandler(IRepositoryWithEvents<SysMenu> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteSysMenuRequest request, CancellationToken cancellationToken)
    {
        var sysMenu = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysMenu ?? throw new NotFoundException(_localizer["sysMenu.notfound"]);

        await _repository.DeleteAsync(sysMenu, cancellationToken);

        return request.Id;
    }
   }

}
