//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteSysRoleUserRelationRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteSysRoleUserRelationRequestValidator : CustomValidator<DeleteSysRoleUserRelationRequest>
    {
       public DeleteSysRoleUserRelationRequestValidator(IReadRepository<SysRoleUserRelation> repository, IStringLocalizer<DeleteSysRoleUserRelationRequestValidator> localizer){}
    }
    public class DeleteSysRoleUserRelationRequestHandler : IRequestHandler<DeleteSysRoleUserRelationRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysRoleUserRelation> _repository;
    private readonly IStringLocalizer<DeleteSysRoleUserRelationRequestHandler> _localizer;

    public DeleteSysRoleUserRelationRequestHandler(IRepositoryWithEvents<SysRoleUserRelation> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteSysRoleUserRelationRequest request, CancellationToken cancellationToken)
    {
        var sysRoleUserRelation = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysRoleUserRelation ?? throw new NotFoundException(_localizer["sysRoleUserRelation.notfound"]);

        await _repository.DeleteAsync(sysRoleUserRelation, cancellationToken);

        return request.Id;
    }
   }

}
