//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteSysDictionaryDataRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteSysDictionaryDataRequestValidator : CustomValidator<DeleteSysDictionaryDataRequest>
    {
       public DeleteSysDictionaryDataRequestValidator(IReadRepository<SysDictionaryData> repository, IStringLocalizer<DeleteSysDictionaryDataRequestValidator> localizer){}
    }
    public class DeleteSysDictionaryDataRequestHandler : IRequestHandler<DeleteSysDictionaryDataRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysDictionaryData> _repository;
    private readonly IStringLocalizer<DeleteSysDictionaryDataRequestHandler> _localizer;

    public DeleteSysDictionaryDataRequestHandler(IRepositoryWithEvents<SysDictionaryData> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteSysDictionaryDataRequest request, CancellationToken cancellationToken)
    {
        var sysDictionaryData = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysDictionaryData ?? throw new NotFoundException(_localizer["sysDictionaryData.notfound"]);

        await _repository.DeleteAsync(sysDictionaryData, cancellationToken);

        return request.Id;
    }
   }

}
