//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurQuestionAnswersRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurQuestionAnswersRequestValidator : CustomValidator<DeleteCurQuestionAnswersRequest>
    {
       public DeleteCurQuestionAnswersRequestValidator(IReadRepository<CurQuestionAnswers> repository, IStringLocalizer<DeleteCurQuestionAnswersRequestValidator> localizer){}
    }
    public class DeleteCurQuestionAnswersRequestHandler : IRequestHandler<DeleteCurQuestionAnswersRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurQuestionAnswers> _repository;
    private readonly IStringLocalizer<DeleteCurQuestionAnswersRequestHandler> _localizer;

    public DeleteCurQuestionAnswersRequestHandler(IRepositoryWithEvents<CurQuestionAnswers> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurQuestionAnswersRequest request, CancellationToken cancellationToken)
    {
        var curQuestionAnswers = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curQuestionAnswers ?? throw new NotFoundException(_localizer["curQuestionAnswers.notfound"]);

        await _repository.DeleteAsync(curQuestionAnswers, cancellationToken);

        return request.Id;
    }
   }

}
