//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurUsersRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurUsersRequestValidator : CustomValidator<DeleteCurUsersRequest>
    {
       public DeleteCurUsersRequestValidator(IReadRepository<CurUsers> repository, IStringLocalizer<DeleteCurUsersRequestValidator> localizer){}
    }
    public class DeleteCurUsersRequestHandler : IRequestHandler<DeleteCurUsersRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurUsers> _repository;
    private readonly IStringLocalizer<DeleteCurUsersRequestHandler> _localizer;

    public DeleteCurUsersRequestHandler(IRepositoryWithEvents<CurUsers> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurUsersRequest request, CancellationToken cancellationToken)
    {
        var curUsers = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curUsers ?? throw new NotFoundException(_localizer["curUsers.notfound"]);

        await _repository.DeleteAsync(curUsers, cancellationToken);

        return request.Id;
    }
   }

}
