//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurClassesRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurClassesRequestValidator : CustomValidator<DeleteCurClassesRequest>
    {
       public DeleteCurClassesRequestValidator(IReadRepository<CurClasses> repository, IStringLocalizer<DeleteCurClassesRequestValidator> localizer){}
    }
    public class DeleteCurClassesRequestHandler : IRequestHandler<DeleteCurClassesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurClasses> _repository;
    private readonly IStringLocalizer<DeleteCurClassesRequestHandler> _localizer;

    public DeleteCurClassesRequestHandler(IRepositoryWithEvents<CurClasses> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurClassesRequest request, CancellationToken cancellationToken)
    {
        var curClasses = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curClasses ?? throw new NotFoundException(_localizer["curClasses.notfound"]);

        await _repository.DeleteAsync(curClasses, cancellationToken);

        return request.Id;
    }
   }

}
