//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurOrganizationsRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurOrganizationsRequestValidator : CustomValidator<DeleteCurOrganizationsRequest>
    {
       public DeleteCurOrganizationsRequestValidator(IReadRepository<CurOrganizations> repository, IStringLocalizer<DeleteCurOrganizationsRequestValidator> localizer){}
    }
    public class DeleteCurOrganizationsRequestHandler : IRequestHandler<DeleteCurOrganizationsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurOrganizations> _repository;
    private readonly IStringLocalizer<DeleteCurOrganizationsRequestHandler> _localizer;

    public DeleteCurOrganizationsRequestHandler(IRepositoryWithEvents<CurOrganizations> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurOrganizationsRequest request, CancellationToken cancellationToken)
    {
        var curOrganizations = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curOrganizations ?? throw new NotFoundException(_localizer["curOrganizations.notfound"]);

        await _repository.DeleteAsync(curOrganizations, cancellationToken);

        return request.Id;
    }
   }

}
