//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurQualificationsRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurQualificationsRequestValidator : CustomValidator<DeleteCurQualificationsRequest>
    {
       public DeleteCurQualificationsRequestValidator(IReadRepository<CurQualifications> repository, IStringLocalizer<DeleteCurQualificationsRequestValidator> localizer){}
    }
    public class DeleteCurQualificationsRequestHandler : IRequestHandler<DeleteCurQualificationsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurQualifications> _repository;
    private readonly IStringLocalizer<DeleteCurQualificationsRequestHandler> _localizer;

    public DeleteCurQualificationsRequestHandler(IRepositoryWithEvents<CurQualifications> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurQualificationsRequest request, CancellationToken cancellationToken)
    {
        var curQualifications = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curQualifications ?? throw new NotFoundException(_localizer["curQualifications.notfound"]);

        await _repository.DeleteAsync(curQualifications, cancellationToken);

        return request.Id;
    }
   }

}
