//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurTeachingMethodsRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurTeachingMethodsRequestValidator : CustomValidator<DeleteCurTeachingMethodsRequest>
    {
       public DeleteCurTeachingMethodsRequestValidator(IReadRepository<CurTeachingMethods> repository, IStringLocalizer<DeleteCurTeachingMethodsRequestValidator> localizer){}
    }
    public class DeleteCurTeachingMethodsRequestHandler : IRequestHandler<DeleteCurTeachingMethodsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurTeachingMethods> _repository;
    private readonly IStringLocalizer<DeleteCurTeachingMethodsRequestHandler> _localizer;

    public DeleteCurTeachingMethodsRequestHandler(IRepositoryWithEvents<CurTeachingMethods> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurTeachingMethodsRequest request, CancellationToken cancellationToken)
    {
        var curTeachingMethods = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curTeachingMethods ?? throw new NotFoundException(_localizer["curTeachingMethods.notfound"]);

        await _repository.DeleteAsync(curTeachingMethods, cancellationToken);

        return request.Id;
    }
   }

}
