//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurEnrollmentsRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurEnrollmentsRequestValidator : CustomValidator<DeleteCurEnrollmentsRequest>
    {
       public DeleteCurEnrollmentsRequestValidator(IReadRepository<CurEnrollments> repository, IStringLocalizer<DeleteCurEnrollmentsRequestValidator> localizer){}
    }
    public class DeleteCurEnrollmentsRequestHandler : IRequestHandler<DeleteCurEnrollmentsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurEnrollments> _repository;
    private readonly IStringLocalizer<DeleteCurEnrollmentsRequestHandler> _localizer;

    public DeleteCurEnrollmentsRequestHandler(IRepositoryWithEvents<CurEnrollments> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurEnrollmentsRequest request, CancellationToken cancellationToken)
    {
        var curEnrollments = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curEnrollments ?? throw new NotFoundException(_localizer["curEnrollments.notfound"]);

        await _repository.DeleteAsync(curEnrollments, cancellationToken);

        return request.Id;
    }
   }

}
