//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurDegreesRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurDegreesRequestValidator : CustomValidator<DeleteCurDegreesRequest>
    {
       public DeleteCurDegreesRequestValidator(IReadRepository<CurDegrees> repository, IStringLocalizer<DeleteCurDegreesRequestValidator> localizer){}
    }
    public class DeleteCurDegreesRequestHandler : IRequestHandler<DeleteCurDegreesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurDegrees> _repository;
    private readonly IStringLocalizer<DeleteCurDegreesRequestHandler> _localizer;

    public DeleteCurDegreesRequestHandler(IRepositoryWithEvents<CurDegrees> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurDegreesRequest request, CancellationToken cancellationToken)
    {
        var curDegrees = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curDegrees ?? throw new NotFoundException(_localizer["curDegrees.notfound"]);

        await _repository.DeleteAsync(curDegrees, cancellationToken);

        return request.Id;
    }
   }

}
