//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteSysEventtrackerRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteSysEventtrackerRequestValidator : CustomValidator<DeleteSysEventtrackerRequest>
    {
       public DeleteSysEventtrackerRequestValidator(IReadRepository<SysEventtracker> repository, IStringLocalizer<DeleteSysEventtrackerRequestValidator> localizer){}
    }
    public class DeleteSysEventtrackerRequestHandler : IRequestHandler<DeleteSysEventtrackerRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysEventtracker> _repository;
    private readonly IStringLocalizer<DeleteSysEventtrackerRequestHandler> _localizer;

    public DeleteSysEventtrackerRequestHandler(IRepositoryWithEvents<SysEventtracker> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteSysEventtrackerRequest request, CancellationToken cancellationToken)
    {
        var sysEventtracker = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysEventtracker ?? throw new NotFoundException(_localizer["sysEventtracker.notfound"]);

        await _repository.DeleteAsync(sysEventtracker, cancellationToken);

        return request.Id;
    }
   }

}
