//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteSysOrganizationRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteSysOrganizationRequestValidator : CustomValidator<DeleteSysOrganizationRequest>
    {
       public DeleteSysOrganizationRequestValidator(IReadRepository<SysOrganization> repository, IStringLocalizer<DeleteSysOrganizationRequestValidator> localizer){}
    }
    public class DeleteSysOrganizationRequestHandler : IRequestHandler<DeleteSysOrganizationRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysOrganization> _repository;
    private readonly IStringLocalizer<DeleteSysOrganizationRequestHandler> _localizer;

    public DeleteSysOrganizationRequestHandler(IRepositoryWithEvents<SysOrganization> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteSysOrganizationRequest request, CancellationToken cancellationToken)
    {
        var sysOrganization = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysOrganization ?? throw new NotFoundException(_localizer["sysOrganization.notfound"]);

        await _repository.DeleteAsync(sysOrganization, cancellationToken);

        return request.Id;
    }
   }

}
