//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteSysRoleMenuRelationRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteSysRoleMenuRelationRequestValidator : CustomValidator<DeleteSysRoleMenuRelationRequest>
    {
       public DeleteSysRoleMenuRelationRequestValidator(IReadRepository<SysRoleMenuRelation> repository, IStringLocalizer<DeleteSysRoleMenuRelationRequestValidator> localizer){}
    }
    public class DeleteSysRoleMenuRelationRequestHandler : IRequestHandler<DeleteSysRoleMenuRelationRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<SysRoleMenuRelation> _repository;
    private readonly IStringLocalizer<DeleteSysRoleMenuRelationRequestHandler> _localizer;

    public DeleteSysRoleMenuRelationRequestHandler(IRepositoryWithEvents<SysRoleMenuRelation> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteSysRoleMenuRelationRequest request, CancellationToken cancellationToken)
    {
        var sysRoleMenuRelation = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = sysRoleMenuRelation ?? throw new NotFoundException(_localizer["sysRoleMenuRelation.notfound"]);

        await _repository.DeleteAsync(sysRoleMenuRelation, cancellationToken);

        return request.Id;
    }
   }

}
