//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurCourseStandardsRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurCourseStandardsRequestValidator : CustomValidator<DeleteCurCourseStandardsRequest>
    {
       public DeleteCurCourseStandardsRequestValidator(IReadRepository<CurCourseStandards> repository, IStringLocalizer<DeleteCurCourseStandardsRequestValidator> localizer){}
    }
    public class DeleteCurCourseStandardsRequestHandler : IRequestHandler<DeleteCurCourseStandardsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurCourseStandards> _repository;
    private readonly IStringLocalizer<DeleteCurCourseStandardsRequestHandler> _localizer;

    public DeleteCurCourseStandardsRequestHandler(IRepositoryWithEvents<CurCourseStandards> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurCourseStandardsRequest request, CancellationToken cancellationToken)
    {
        var curCourseStandards = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curCourseStandards ?? throw new NotFoundException(_localizer["curCourseStandards.notfound"]);

        await _repository.DeleteAsync(curCourseStandards, cancellationToken);

        return request.Id;
    }
   }

}
