//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurLrsLogsRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurLrsLogsRequestValidator : CustomValidator<DeleteCurLrsLogsRequest>
    {
       public DeleteCurLrsLogsRequestValidator(IReadRepository<CurLrsLogs> repository, IStringLocalizer<DeleteCurLrsLogsRequestValidator> localizer){}
    }
    public class DeleteCurLrsLogsRequestHandler : IRequestHandler<DeleteCurLrsLogsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurLrsLogs> _repository;
    private readonly IStringLocalizer<DeleteCurLrsLogsRequestHandler> _localizer;

    public DeleteCurLrsLogsRequestHandler(IRepositoryWithEvents<CurLrsLogs> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurLrsLogsRequest request, CancellationToken cancellationToken)
    {
        var curLrsLogs = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curLrsLogs ?? throw new NotFoundException(_localizer["curLrsLogs.notfound"]);

        await _repository.DeleteAsync(curLrsLogs, cancellationToken);

        return request.Id;
    }
   }

}
