//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurTeacherTypesRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurTeacherTypesRequestValidator : CustomValidator<DeleteCurTeacherTypesRequest>
    {
       public DeleteCurTeacherTypesRequestValidator(IReadRepository<CurTeacherTypes> repository, IStringLocalizer<DeleteCurTeacherTypesRequestValidator> localizer){}
    }
    public class DeleteCurTeacherTypesRequestHandler : IRequestHandler<DeleteCurTeacherTypesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurTeacherTypes> _repository;
    private readonly IStringLocalizer<DeleteCurTeacherTypesRequestHandler> _localizer;

    public DeleteCurTeacherTypesRequestHandler(IRepositoryWithEvents<CurTeacherTypes> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurTeacherTypesRequest request, CancellationToken cancellationToken)
    {
        var curTeacherTypes = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curTeacherTypes ?? throw new NotFoundException(_localizer["curTeacherTypes.notfound"]);

        await _repository.DeleteAsync(curTeacherTypes, cancellationToken);

        return request.Id;
    }
   }

}
