//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurTeachersRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurTeachersRequestValidator : CustomValidator<DeleteCurTeachersRequest>
    {
       public DeleteCurTeachersRequestValidator(IReadRepository<CurTeachers> repository, IStringLocalizer<DeleteCurTeachersRequestValidator> localizer){}
    }
    public class DeleteCurTeachersRequestHandler : IRequestHandler<DeleteCurTeachersRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurTeachers> _repository;
    private readonly IStringLocalizer<DeleteCurTeachersRequestHandler> _localizer;

    public DeleteCurTeachersRequestHandler(IRepositoryWithEvents<CurTeachers> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurTeachersRequest request, CancellationToken cancellationToken)
    {
        var curTeachers = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curTeachers ?? throw new NotFoundException(_localizer["curTeachers.notfound"]);

        await _repository.DeleteAsync(curTeachers, cancellationToken);

        return request.Id;
    }
   }

}
