//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurMaritalStatusesRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurMaritalStatusesRequestValidator : CustomValidator<DeleteCurMaritalStatusesRequest>
    {
       public DeleteCurMaritalStatusesRequestValidator(IReadRepository<CurMaritalStatuses> repository, IStringLocalizer<DeleteCurMaritalStatusesRequestValidator> localizer){}
    }
    public class DeleteCurMaritalStatusesRequestHandler : IRequestHandler<DeleteCurMaritalStatusesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurMaritalStatuses> _repository;
    private readonly IStringLocalizer<DeleteCurMaritalStatusesRequestHandler> _localizer;

    public DeleteCurMaritalStatusesRequestHandler(IRepositoryWithEvents<CurMaritalStatuses> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurMaritalStatusesRequest request, CancellationToken cancellationToken)
    {
        var curMaritalStatuses = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curMaritalStatuses ?? throw new NotFoundException(_localizer["curMaritalStatuses.notfound"]);

        await _repository.DeleteAsync(curMaritalStatuses, cancellationToken);

        return request.Id;
    }
   }

}
