//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.delete
{

    public class DeleteCurCourseContentsRequest : IRequest<Int64>
    {
      public Int64 Id { get; set; }
    }
    public class DeleteCurCourseContentsRequestValidator : CustomValidator<DeleteCurCourseContentsRequest>
    {
       public DeleteCurCourseContentsRequestValidator(IReadRepository<CurCourseContents> repository, IStringLocalizer<DeleteCurCourseContentsRequestValidator> localizer){}
    }
    public class DeleteCurCourseContentsRequestHandler : IRequestHandler<DeleteCurCourseContentsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<CurCourseContents> _repository;
    private readonly IStringLocalizer<DeleteCurCourseContentsRequestHandler> _localizer;

    public DeleteCurCourseContentsRequestHandler(IRepositoryWithEvents<CurCourseContents> repository, IStringLocalizer<UpdateBrandRequestHandler> localizer) => (_repository, _localizer) = (repository, localizer);

    public async Task<Int64> Handle(DeleteCurCourseContentsRequest request, CancellationToken cancellationToken)
    {
        var curCourseContents = await _repository.GetByIdAsync(request.Id, cancellationToken);

        _ = curCourseContents ?? throw new NotFoundException(_localizer["curCourseContents.notfound"]);

        await _repository.DeleteAsync(curCourseContents, cancellationToken);

        return request.Id;
    }
   }

}
