export const SCROLL_SIZE_KEYS = {
  DASHBOARD: {
    ROOT: 'DASHBOARD_ROOT',
    TAB: {
      CONTENT_ROOT: 'DASHBOARD_TAB_CONTENT_ROOT',
      LIST_ROOT: 'DASHBOARD_TAB_LIST_ROOT',
    },
    PAGES: {
      APP: {
        MATCH_MENU_LIST: 'DASHBOARD_PAGES_APP_MATCH_MENU_LIST',
        MATCH_MENU_FILTER: 'DASHBOARD_PAGES_APP_MATCH_MENU_FILTER',
        APP_FEATURED_GRID_ITEM: 'DASHBOARD_APP_APP_FEATURED_GRID_ITEM',
      },
    },
  },
}
