//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class CurAssignmentSubmissions : EfFullAuditEntity, ICloneable {

        public CurAssignmentSubmissions()
        {
            this.Isdeleted = false;
            OnCreated();
        }

        public long AssignmentId { get; set; }

        public string? Comment { get; set; }

        public string? FileUrl { get; set; }

        public bool Isdeleted { get; set; }

        public DateTime? ReviewedAt { get; set; }

        public long? ReviewedBy { get; set; }

        public decimal? Score { get; set; }

        public long StudentId { get; set; }

        public DateTime? SubmittedAt { get; set; }

        public virtual CurAssignments CurAssignments { get; set; }

        public virtual CurUsers CurUsers_StudentId { get; set; }

        public virtual CurUsers CurUsers_ReviewedBy { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CurAssignmentSubmissions toCompare = obj as CurAssignmentSubmissions;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CurAssignmentSubmissions obj = new CurAssignmentSubmissions();
            obj.AssignmentId = AssignmentId;
            obj.Comment = Comment;
            obj.FileUrl = FileUrl;
            obj.Isdeleted = Isdeleted;
            obj.ReviewedAt = ReviewedAt;
            obj.ReviewedBy = ReviewedBy;
            obj.Score = Score;
            obj.StudentId = StudentId;
            obj.SubmittedAt = SubmittedAt;
            return obj;
        }

        #endregion
    }

}
