//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class CurEnrollments : EfFullAuditEntity, ICloneable {

        public CurEnrollments()
        {
            this.Isdeleted = false;
            this.Status = @"active";
            OnCreated();
        }

        public long ClassId { get; set; }

        public DateTime? EnrolledAt { get; set; }

        public bool Isdeleted { get; set; }

        public string? Status { get; set; }

        public long StudentId { get; set; }

        public virtual CurClasses CurClasses { get; set; }

        public virtual CurUsers CurUsers { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CurEnrollments toCompare = obj as CurEnrollments;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CurEnrollments obj = new CurEnrollments();
            obj.ClassId = ClassId;
            obj.EnrolledAt = EnrolledAt;
            obj.Isdeleted = Isdeleted;
            obj.Status = Status;
            obj.StudentId = StudentId;
            return obj;
        }

        #endregion
    }

}
