//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class CurLrsLogs : EfFullAuditEntity, ICloneable {

        public CurLrsLogs()
        {
            this.Isdeleted = false;
            OnCreated();
        }

        public string? Context { get; set; }

        public long? CourseId { get; set; }

        public bool Isdeleted { get; set; }

        public string? Object { get; set; }

        public string? Result { get; set; }

        public string? StatementId { get; set; }

        public DateTime? Timestamp { get; set; }

        public long UserId { get; set; }

        public string? Verb { get; set; }

        public virtual CurUsers CurUsers { get; set; }

        public virtual CurCourses CurCourses { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CurLrsLogs toCompare = obj as CurLrsLogs;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CurLrsLogs obj = new CurLrsLogs();
            obj.Context = Context;
            obj.CourseId = CourseId;
            obj.Isdeleted = Isdeleted;
            obj.Object = Object;
            obj.Result = Result;
            obj.StatementId = StatementId;
            obj.Timestamp = Timestamp;
            obj.UserId = UserId;
            obj.Verb = Verb;
            return obj;
        }

        #endregion
    }

}
