//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class CurQuestions : EfFullAuditEntity, ICloneable {

        public CurQuestions()
        {
            this.Isdeleted = false;
            this.Score = 1;
            this.CurAnswers = new List<CurAnswers>();
            this.CurQuestionAnswers = new List<CurQuestionAnswers>();
            OnCreated();
        }

        public bool Isdeleted { get; set; }

        public long QuizId { get; set; }

        public int? Score { get; set; }

        public string? Text { get; set; }

        public string Type { get; set; }

        public virtual IList<CurAnswers> CurAnswers { get; set; }

        public virtual IList<CurQuestionAnswers> CurQuestionAnswers { get; set; }

        public virtual CurQuizzes CurQuizzes { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CurQuestions toCompare = obj as CurQuestions;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CurQuestions obj = new CurQuestions();
            obj.Isdeleted = Isdeleted;
            obj.QuizId = QuizId;
            obj.Score = Score;
            obj.Text = Text;
            obj.Type = Type;
            return obj;
        }

        #endregion
    }

}
