//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class CurQuestionAnswers : EfFullAuditEntity, ICloneable {

        public CurQuestionAnswers()
        {
            this.Isdeleted = false;
            this.Score = 0.00m;
            OnCreated();
        }

        public string? AnswerText { get; set; }

        public bool Isdeleted { get; set; }

        public long QuestionId { get; set; }

        public decimal? Score { get; set; }

        public string? SelectedOptionIds { get; set; }

        public long SubmissionId { get; set; }

        public virtual CurQuizSubmissions CurQuizSubmissions { get; set; }

        public virtual CurQuestions CurQuestions { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CurQuestionAnswers toCompare = obj as CurQuestionAnswers;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CurQuestionAnswers obj = new CurQuestionAnswers();
            obj.AnswerText = AnswerText;
            obj.Isdeleted = Isdeleted;
            obj.QuestionId = QuestionId;
            obj.Score = Score;
            obj.SelectedOptionIds = SelectedOptionIds;
            obj.SubmissionId = SubmissionId;
            return obj;
        }

        #endregion
    }

}
