//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class CurQuizzes : EfFullAuditEntity, ICloneable {

        public CurQuizzes()
        {
            this.Isdeleted = false;
            this.CurQuestions = new List<CurQuestions>();
            OnCreated();
        }

        public long ClassId { get; set; }

        public long? CreatedBy { get; set; }

        public string? Description { get; set; }

        public int? DurationMinutes { get; set; }

        public DateTime? EndTime { get; set; }

        public bool Isdeleted { get; set; }

        public DateTime? StartTime { get; set; }

        public string? Title { get; set; }

        public int? TotalScore { get; set; }

        public virtual IList<CurQuestions> CurQuestions { get; set; }

        public virtual CurQuizSubmissions CurQuizSubmissions { get; set; }

        public virtual CurClasses CurClasses { get; set; }

        public virtual CurUsers CurUsers { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CurQuizzes toCompare = obj as CurQuizzes;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CurQuizzes obj = new CurQuizzes();
            obj.ClassId = ClassId;
            obj.CreatedBy = CreatedBy;
            obj.Description = Description;
            obj.DurationMinutes = DurationMinutes;
            obj.EndTime = EndTime;
            obj.Isdeleted = Isdeleted;
            obj.StartTime = StartTime;
            obj.Title = Title;
            obj.TotalScore = TotalScore;
            return obj;
        }

        #endregion
    }

}
