//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class CurQualifications : EfFullAuditEntity, ICloneable {

        public CurQualifications()
        {
            this.Isdeleted = false;
            OnCreated();
        }

        public bool Isdeleted { get; set; }

        public string QualificationLevel { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CurQualifications toCompare = obj as CurQualifications;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CurQualifications obj = new CurQualifications();
            obj.Isdeleted = Isdeleted;
            obj.QualificationLevel = QualificationLevel;
            return obj;
        }

        #endregion
    }

}
