//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    /// <summary>
    /// Dictionary Data
    /// </summary>
    [Serializable()]
    public partial class SysDictionaryData : EfFullAuditEntity, ICloneable {

        public SysDictionaryData()
        {
            OnCreated();
        }

        public string Dictcode { get; set; }

        public string Label { get; set; }

        public int Ordinal { get; set; }

        public bool Status { get; set; }

        public string Tagtype { get; set; }

        public string Value { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          SysDictionaryData toCompare = obj as SysDictionaryData;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            SysDictionaryData obj = new SysDictionaryData();
            obj.Dictcode = Dictcode;
            obj.Label = Label;
            obj.Ordinal = Ordinal;
            obj.Status = Status;
            obj.Tagtype = Tagtype;
            obj.Value = Value;
            return obj;
        }

        #endregion
    }

}
