//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    /// <summary>
    /// Menu
    /// </summary>
    [Serializable()]
    public partial class SysMenu : EfFullAuditEntity, ICloneable {

        public SysMenu()
        {
            OnCreated();
        }

        /// <summary>
        /// Always Show Single Child Route
        /// </summary>
        public bool Alwaysshow { get; set; }

        /// <summary>
        /// Component Configuration
        /// </summary>
        public string Component { get; set; }

        /// <summary>
        /// Icon
        /// </summary>
        public string Icon { get; set; }

        /// <summary>
        /// Enable Page Cache
        /// </summary>
        public bool Keepalive { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Order Number
        /// </summary>
        public int Ordinal { get; set; }

        /// <summary>
        /// Route Parameters
        /// </summary>
        public string Params { get; set; }

        /// <summary>
        /// Parent Menu ID
        /// </summary>
        public long Parentid { get; set; }

        /// <summary>
        /// Parent Menu IDs
        /// </summary>
        public string Parentids { get; set; }

        /// <summary>
        /// Permission Code
        /// </summary>
        public string Perm { get; set; }

        /// <summary>
        /// Redirect Route Path
        /// </summary>
        public string Redirect { get; set; }

        /// <summary>
        /// Route Name
        /// </summary>
        public string Routename { get; set; }

        /// <summary>
        /// Route Path
        /// </summary>
        public string Routepath { get; set; }

        /// <summary>
        /// Menu Type
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        /// Is Visible
        /// </summary>
        public bool Visible { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          SysMenu toCompare = obj as SysMenu;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            SysMenu obj = new SysMenu();
            obj.Alwaysshow = Alwaysshow;
            obj.Component = Component;
            obj.Icon = Icon;
            obj.Keepalive = Keepalive;
            obj.Name = Name;
            obj.Ordinal = Ordinal;
            obj.Params = Params;
            obj.Parentid = Parentid;
            obj.Parentids = Parentids;
            obj.Perm = Perm;
            obj.Redirect = Redirect;
            obj.Routename = Routename;
            obj.Routepath = Routepath;
            obj.Type = Type;
            obj.Visible = Visible;
            return obj;
        }

        #endregion
    }

}
