//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    /// <summary>
    /// Role
    /// </summary>
    [Serializable()]
    public partial class SysRole : EfFullAuditEntity, ICloneable {

        public SysRole()
        {
            OnCreated();
        }

        /// <summary>
        /// Code
        /// </summary>
        public string Code { get; set; }

        /// <summary>
        /// Data Scope
        /// </summary>
        public int Datascope { get; set; }

        public string? FkMenu { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Order Number
        /// </summary>
        public int Ordinal { get; set; }

        /// <summary>
        /// Status
        /// </summary>
        public bool Status { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          SysRole toCompare = obj as SysRole;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            SysRole obj = new SysRole();
            obj.Code = Code;
            obj.Datascope = Datascope;
            obj.FkMenu = FkMenu;
            obj.Name = Name;
            obj.Ordinal = Ordinal;
            obj.Status = Status;
            return obj;
        }

        #endregion
    }

}
