//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class SysUserType : EfFullAuditEntity, ICloneable {

        public SysUserType()
        {
            this.IsDeleted = false;
            this.SysUsers = new List<SysUser>();
            OnCreated();
        }

        public bool IsDeleted { get; set; }

        public string? Name { get; set; }

        public virtual IList<SysUser> SysUsers { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          SysUserType toCompare = obj as SysUserType;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            SysUserType obj = new SysUserType();
            obj.IsDeleted = IsDeleted;
            obj.Name = Name;
            return obj;
        }

        #endregion
    }

}
