//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.create
{

    public class CreateSysUserTypeRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool IsDeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        #endregion
    }
    public class CreateSysUserTypeRequestValidator : CustomValidator<CreateSysUserTypeRequest>
    {
       public CreateSysUserTypeRequestValidator(IReadRepository<SysUserType> repository, IStringLocalizer<CreateSysUserTypeRequestValidator> localizer){}
    }
    public class CreateSysUserTypeRequestHandler : IRequestHandler<CreateSysUserTypeRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<Brand> _repository;

    public CreateSysUserTypeRequestHandler(IRepositoryWithEvents<SysUserType> repository) => _repository = repository;

    public async Task<Int64> Handle(CreateSysUserTypeRequest request, CancellationToken cancellationToken)
    {
        var sysUserType = new SysUserType(Createby,Createtime,IsDeleted,Modifyby,Modifytime,Name)

        await _repository.AddAsync(sysUserType, cancellationToken);

        return SysUserType.Id;
    }
   }

}
