//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.create
{

    public class CreateSysConfigRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public string Key { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        public string Remark { get; set; }

        public string Value { get; set; }

        #endregion
    }
    public class CreateSysConfigRequestValidator : CustomValidator<CreateSysConfigRequest>
    {
       public CreateSysConfigRequestValidator(IReadRepository<SysConfig> repository, IStringLocalizer<CreateSysConfigRequestValidator> localizer){}
    }
    public class CreateSysConfigRequestHandler : IRequestHandler<CreateSysConfigRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<Brand> _repository;

    public CreateSysConfigRequestHandler(IRepositoryWithEvents<SysConfig> repository) => _repository = repository;

    public async Task<Int64> Handle(CreateSysConfigRequest request, CancellationToken cancellationToken)
    {
        var sysConfig = new SysConfig(Createby,Createtime,Key,Modifyby,Modifytime,Name,Remark,Value)

        await _repository.AddAsync(sysConfig, cancellationToken);

        return SysConfig.Id;
    }
   }

}
