//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.create
{

    public class CreateCurQualificationsRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string QualificationLevel { get; set; }

        #endregion
    }
    public class CreateCurQualificationsRequestValidator : CustomValidator<CreateCurQualificationsRequest>
    {
       public CreateCurQualificationsRequestValidator(IReadRepository<CurQualifications> repository, IStringLocalizer<CreateCurQualificationsRequestValidator> localizer){}
    }
    public class CreateCurQualificationsRequestHandler : IRequestHandler<CreateCurQualificationsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<Brand> _repository;

    public CreateCurQualificationsRequestHandler(IRepositoryWithEvents<CurQualifications> repository) => _repository = repository;

    public async Task<Int64> Handle(CreateCurQualificationsRequest request, CancellationToken cancellationToken)
    {
        var curQualifications = new CurQualifications(Createby,Createtime,Isdeleted,Modifyby,Modifytime,QualificationLevel)

        await _repository.AddAsync(curQualifications, cancellationToken);

        return CurQualifications.Id;
    }
   }

}
