//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.create
{

    public class CreateCurFieldsOfStudyRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public int Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        #endregion
    }
    public class CreateCurFieldsOfStudyRequestValidator : CustomValidator<CreateCurFieldsOfStudyRequest>
    {
       public CreateCurFieldsOfStudyRequestValidator(IReadRepository<CurFieldsOfStudy> repository, IStringLocalizer<CreateCurFieldsOfStudyRequestValidator> localizer){}
    }
    public class CreateCurFieldsOfStudyRequestHandler : IRequestHandler<CreateCurFieldsOfStudyRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<Brand> _repository;

    public CreateCurFieldsOfStudyRequestHandler(IRepositoryWithEvents<CurFieldsOfStudy> repository) => _repository = repository;

    public async Task<Int64> Handle(CreateCurFieldsOfStudyRequest request, CancellationToken cancellationToken)
    {
        var curFieldsOfStudy = new CurFieldsOfStudy(Createby,Createtime,Isdeleted,Modifyby,Modifytime,Name)

        await _repository.AddAsync(curFieldsOfStudy, cancellationToken);

        return CurFieldsOfStudy.Id;
    }
   }

}
