//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.create
{

    public class CreateCurClassesRequest : IRequest<Int64>
    {

        #region Properties

        public long CourseId { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public System.DateTime? EndDate { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public int? MaxStudents { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public System.DateTime? StartDate { get; set; }

        public string Status { get; set; }

        public long TeacherId { get; set; }

        #endregion
    }
    public class CreateCurClassesRequestValidator : CustomValidator<CreateCurClassesRequest>
    {
       public CreateCurClassesRequestValidator(IReadRepository<CurClasses> repository, IStringLocalizer<CreateCurClassesRequestValidator> localizer){}
    }
    public class CreateCurClassesRequestHandler : IRequestHandler<CreateCurClassesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<Brand> _repository;

    public CreateCurClassesRequestHandler(IRepositoryWithEvents<CurClasses> repository) => _repository = repository;

    public async Task<Int64> Handle(CreateCurClassesRequest request, CancellationToken cancellationToken)
    {
        var curClasses = new CurClasses(CourseId,Createby,Createtime,EndDate,Isdeleted,MaxStudents,Modifyby,Modifytime,StartDate,Status,TeacherId)

        await _repository.AddAsync(curClasses, cancellationToken);

        return CurClasses.Id;
    }
   }

}
