//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.create
{

    public class CreateCurOrganizationsRequest : IRequest<Int64>
    {

        #region Properties

        public string Code { get; set; }

        public long Createby { get; set; }

        public System.DateTime? CreatedAt { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public int? Level { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        public long? ParentId { get; set; }

        public string Path { get; set; }

        public string Type { get; set; }

        public System.DateTime? UpdatedAt { get; set; }

        #endregion
    }
    public class CreateCurOrganizationsRequestValidator : CustomValidator<CreateCurOrganizationsRequest>
    {
       public CreateCurOrganizationsRequestValidator(IReadRepository<CurOrganizations> repository, IStringLocalizer<CreateCurOrganizationsRequestValidator> localizer){}
    }
    public class CreateCurOrganizationsRequestHandler : IRequestHandler<CreateCurOrganizationsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<Brand> _repository;

    public CreateCurOrganizationsRequestHandler(IRepositoryWithEvents<CurOrganizations> repository) => _repository = repository;

    public async Task<Int64> Handle(CreateCurOrganizationsRequest request, CancellationToken cancellationToken)
    {
        var curOrganizations = new CurOrganizations(Code,Createby,CreatedAt,Createtime,Isdeleted,Level,Modifyby,Modifytime,Name,ParentId,Path,Type,UpdatedAt)

        await _repository.AddAsync(curOrganizations, cancellationToken);

        return CurOrganizations.Id;
    }
   }

}
