//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.create
{

    public class CreateCurQuestionsRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public long QuizId { get; set; }

        public int? Score { get; set; }

        public string Text { get; set; }

        public string Type { get; set; }

        #endregion
    }
    public class CreateCurQuestionsRequestValidator : CustomValidator<CreateCurQuestionsRequest>
    {
       public CreateCurQuestionsRequestValidator(IReadRepository<CurQuestions> repository, IStringLocalizer<CreateCurQuestionsRequestValidator> localizer){}
    }
    public class CreateCurQuestionsRequestHandler : IRequestHandler<CreateCurQuestionsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<Brand> _repository;

    public CreateCurQuestionsRequestHandler(IRepositoryWithEvents<CurQuestions> repository) => _repository = repository;

    public async Task<Int64> Handle(CreateCurQuestionsRequest request, CancellationToken cancellationToken)
    {
        var curQuestions = new CurQuestions(Createby,Createtime,Isdeleted,Modifyby,Modifytime,QuizId,Score,Text,Type)

        await _repository.AddAsync(curQuestions, cancellationToken);

        return CurQuestions.Id;
    }
   }

}
