//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.create
{

    public class CreateCurAnswersRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool? IsCorrect { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public long QuestionId { get; set; }

        public string Text { get; set; }

        #endregion
    }
    public class CreateCurAnswersRequestValidator : CustomValidator<CreateCurAnswersRequest>
    {
       public CreateCurAnswersRequestValidator(IReadRepository<CurAnswers> repository, IStringLocalizer<CreateCurAnswersRequestValidator> localizer){}
    }
    public class CreateCurAnswersRequestHandler : IRequestHandler<CreateCurAnswersRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<Brand> _repository;

    public CreateCurAnswersRequestHandler(IRepositoryWithEvents<CurAnswers> repository) => _repository = repository;

    public async Task<Int64> Handle(CreateCurAnswersRequest request, CancellationToken cancellationToken)
    {
        var curAnswers = new CurAnswers(Createby,Createtime,IsCorrect,Isdeleted,Modifyby,Modifytime,QuestionId,Text)

        await _repository.AddAsync(curAnswers, cancellationToken);

        return CurAnswers.Id;
    }
   }

}
