//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.create
{

    public class CreateSysEventtrackerRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Eventid { get; set; }

        public long Id { get; set; }

        public string Trackername { get; set; }

        #endregion
    }
    public class CreateSysEventtrackerRequestValidator : CustomValidator<CreateSysEventtrackerRequest>
    {
       public CreateSysEventtrackerRequestValidator(IReadRepository<SysEventtracker> repository, IStringLocalizer<CreateSysEventtrackerRequestValidator> localizer){}
    }
    public class CreateSysEventtrackerRequestHandler : IRequestHandler<CreateSysEventtrackerRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<Brand> _repository;

    public CreateSysEventtrackerRequestHandler(IRepositoryWithEvents<SysEventtracker> repository) => _repository = repository;

    public async Task<Int64> Handle(CreateSysEventtrackerRequest request, CancellationToken cancellationToken)
    {
        var sysEventtracker = new SysEventtracker(Createby,Createtime,Eventid,Trackername)

        await _repository.AddAsync(sysEventtracker, cancellationToken);

        return SysEventtracker.Id;
    }
   }

}
