//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.create
{

    public class CreateSysOrganizationRequest : IRequest<Int64>
    {

        #region Properties

        public string Code { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public long Modifyby { get; set; }

        public System.DateTime Modifytime { get; set; }

        public string Name { get; set; }

        public int Ordinal { get; set; }

        public long Parentid { get; set; }

        public string Parentids { get; set; }

        public bool Status { get; set; }

        #endregion
    }
    public class CreateSysOrganizationRequestValidator : CustomValidator<CreateSysOrganizationRequest>
    {
       public CreateSysOrganizationRequestValidator(IReadRepository<SysOrganization> repository, IStringLocalizer<CreateSysOrganizationRequestValidator> localizer){}
    }
    public class CreateSysOrganizationRequestHandler : IRequestHandler<CreateSysOrganizationRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<Brand> _repository;

    public CreateSysOrganizationRequestHandler(IRepositoryWithEvents<SysOrganization> repository) => _repository = repository;

    public async Task<Int64> Handle(CreateSysOrganizationRequest request, CancellationToken cancellationToken)
    {
        var sysOrganization = new SysOrganization(Code,Createby,Createtime,Modifyby,Modifytime,Name,Ordinal,Parentid,Parentids,Status)

        await _repository.AddAsync(sysOrganization, cancellationToken);

        return SysOrganization.Id;
    }
   }

}
