//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.create
{

    public class CreateCurTeacherTypesRequest : IRequest<Int64>
    {

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public int Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        #endregion
    }
    public class CreateCurTeacherTypesRequestValidator : CustomValidator<CreateCurTeacherTypesRequest>
    {
       public CreateCurTeacherTypesRequestValidator(IReadRepository<CurTeacherTypes> repository, IStringLocalizer<CreateCurTeacherTypesRequestValidator> localizer){}
    }
    public class CreateCurTeacherTypesRequestHandler : IRequestHandler<CreateCurTeacherTypesRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<Brand> _repository;

    public CreateCurTeacherTypesRequestHandler(IRepositoryWithEvents<CurTeacherTypes> repository) => _repository = repository;

    public async Task<Int64> Handle(CreateCurTeacherTypesRequest request, CancellationToken cancellationToken)
    {
        var curTeacherTypes = new CurTeacherTypes(Createby,Createtime,Isdeleted,Modifyby,Modifytime,Name)

        await _repository.AddAsync(curTeacherTypes, cancellationToken);

        return CurTeacherTypes.Id;
    }
   }

}
