//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.create
{

    public class CreateCurCourseStandardsRequest : IRequest<Int64>
    {

        #region Properties

        public int? CourseId { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string StandardDescription { get; set; }

        #endregion
    }
    public class CreateCurCourseStandardsRequestValidator : CustomValidator<CreateCurCourseStandardsRequest>
    {
       public CreateCurCourseStandardsRequestValidator(IReadRepository<CurCourseStandards> repository, IStringLocalizer<CreateCurCourseStandardsRequestValidator> localizer){}
    }
    public class CreateCurCourseStandardsRequestHandler : IRequestHandler<CreateCurCourseStandardsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<Brand> _repository;

    public CreateCurCourseStandardsRequestHandler(IRepositoryWithEvents<CurCourseStandards> repository) => _repository = repository;

    public async Task<Int64> Handle(CreateCurCourseStandardsRequest request, CancellationToken cancellationToken)
    {
        var curCourseStandards = new CurCourseStandards(CourseId,Createby,Createtime,Isdeleted,Modifyby,Modifytime,StandardDescription)

        await _repository.AddAsync(curCourseStandards, cancellationToken);

        return CurCourseStandards.Id;
    }
   }

}
