//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.create
{

    public class CreateCurEnrollmentsRequest : IRequest<Int64>
    {

        #region Properties

        public long ClassId { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public System.DateTime? EnrolledAt { get; set; }

        public long Id { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Status { get; set; }

        public long StudentId { get; set; }

        #endregion
    }
    public class CreateCurEnrollmentsRequestValidator : CustomValidator<CreateCurEnrollmentsRequest>
    {
       public CreateCurEnrollmentsRequestValidator(IReadRepository<CurEnrollments> repository, IStringLocalizer<CreateCurEnrollmentsRequestValidator> localizer){}
    }
    public class CreateCurEnrollmentsRequestHandler : IRequestHandler<CreateCurEnrollmentsRequest, Int64>
    {
    // Add Domain Events automatically by using IRepositoryWithEvents
    private readonly IRepositoryWithEvents<Brand> _repository;

    public CreateCurEnrollmentsRequestHandler(IRepositoryWithEvents<CurEnrollments> repository) => _repository = repository;

    public async Task<Int64> Handle(CreateCurEnrollmentsRequest request, CancellationToken cancellationToken)
    {
        var curEnrollments = new CurEnrollments(ClassId,Createby,Createtime,EnrolledAt,Isdeleted,Modifyby,Modifytime,Status,StudentId)

        await _repository.AddAsync(curEnrollments, cancellationToken);

        return CurEnrollments.Id;
    }
   }

}
