//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurAttendancesDto
    {
        #region Constructors

        public CurAttendancesDto() {
        }

        public CurAttendancesDto(long classId, long createby, System.DateTime? createdAt, System.DateTime createtime, bool isdeleted, long? modifyby, System.DateTime? modifytime, System.DateTime sessionDate, string status, long studentId, System.DateTime? updatedAt, CurClassesDto curClasses, CurUsersDto curUsers) {

          this.ClassId = classId;
          this.Createby = createby;
          this.CreatedAt = createdAt;
          this.Createtime = createtime;
          this.Isdeleted = isdeleted;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.SessionDate = sessionDate;
          this.Status = status;
          this.StudentId = studentId;
          this.UpdatedAt = updatedAt;
          this.CurClasses = curClasses;
          this.CurUsers = curUsers;
        }

        #endregion

        #region Properties

        public long ClassId { get; set; }

        public long Createby { get; set; }

        public System.DateTime? CreatedAt { get; set; }

        public System.DateTime Createtime { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public System.DateTime SessionDate { get; set; }

        public string Status { get; set; }

        public long StudentId { get; set; }

        public System.DateTime? UpdatedAt { get; set; }

        #endregion

        #region Navigation Properties

        public CurClassesDto CurClasses { get; set; }

        public CurUsersDto CurUsers { get; set; }

        #endregion
    }

}
