//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurAssignmentsDto
    {
        #region Constructors

        public CurAssignmentsDto() {
        }

        public CurAssignmentsDto(long classId, long createby, System.DateTime? createdAt, System.DateTime createtime, string description, System.DateTime? dueDate, bool isdeleted, int? maxScore, long? modifyby, System.DateTime? modifytime, string title, List<CurAssignmentSubmissionsDto> curAssignmentSubmissions, CurClassesDto curClasses, CurUsersDto curUsers) {

          this.ClassId = classId;
          this.Createby = createby;
          this.CreatedAt = createdAt;
          this.Createtime = createtime;
          this.Description = description;
          this.DueDate = dueDate;
          this.Isdeleted = isdeleted;
          this.MaxScore = maxScore;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.Title = title;
          this.CurAssignmentSubmissions = curAssignmentSubmissions;
          this.CurClasses = curClasses;
          this.CurUsers = curUsers;
        }

        #endregion

        #region Properties

        public long ClassId { get; set; }

        public long Createby { get; set; }

        public System.DateTime? CreatedAt { get; set; }

        public System.DateTime Createtime { get; set; }

        public string Description { get; set; }

        public System.DateTime? DueDate { get; set; }

        public bool Isdeleted { get; set; }

        public int? MaxScore { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Title { get; set; }

        #endregion

        #region Navigation Properties

        public List<CurAssignmentSubmissionsDto> CurAssignmentSubmissions { get; set; }

        public CurClassesDto CurClasses { get; set; }

        public CurUsersDto CurUsers { get; set; }

        #endregion
    }

}
