//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurAnswersDto
    {
        #region Constructors

        public CurAnswersDto() {
        }

        public CurAnswersDto(long createby, System.DateTime createtime, bool? isCorrect, bool isdeleted, long? modifyby, System.DateTime? modifytime, long questionId, string text, CurQuestionsDto curQuestions) {

          this.Createby = createby;
          this.Createtime = createtime;
          this.IsCorrect = isCorrect;
          this.Isdeleted = isdeleted;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.QuestionId = questionId;
          this.Text = text;
          this.CurQuestions = curQuestions;
        }

        #endregion

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public bool? IsCorrect { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public long QuestionId { get; set; }

        public string Text { get; set; }

        #endregion

        #region Navigation Properties

        public CurQuestionsDto CurQuestions { get; set; }

        #endregion
    }

}
