//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurAssignmentSubmissionsDto
    {
        #region Constructors

        public CurAssignmentSubmissionsDto() {
        }

        public CurAssignmentSubmissionsDto(long assignmentId, string comment, long createby, System.DateTime createtime, string fileUrl, bool isdeleted, long? modifyby, System.DateTime? modifytime, System.DateTime? reviewedAt, long? reviewedBy, decimal? score, long studentId, System.DateTime? submittedAt, CurAssignmentsDto curAssignments, CurUsersDto curUsers_StudentId, CurUsersDto curUsers_ReviewedBy) {

          this.AssignmentId = assignmentId;
          this.Comment = comment;
          this.Createby = createby;
          this.Createtime = createtime;
          this.FileUrl = fileUrl;
          this.Isdeleted = isdeleted;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.ReviewedAt = reviewedAt;
          this.ReviewedBy = reviewedBy;
          this.Score = score;
          this.StudentId = studentId;
          this.SubmittedAt = submittedAt;
          this.CurAssignments = curAssignments;
          this.CurUsers_StudentId = curUsers_StudentId;
          this.CurUsers_ReviewedBy = curUsers_ReviewedBy;
        }

        #endregion

        #region Properties

        public long AssignmentId { get; set; }

        public string Comment { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public string FileUrl { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public System.DateTime? ReviewedAt { get; set; }

        public long? ReviewedBy { get; set; }

        public decimal? Score { get; set; }

        public long StudentId { get; set; }

        public System.DateTime? SubmittedAt { get; set; }

        #endregion

        #region Navigation Properties

        public CurAssignmentsDto CurAssignments { get; set; }

        public CurUsersDto CurUsers_StudentId { get; set; }

        public CurUsersDto CurUsers_ReviewedBy { get; set; }

        #endregion
    }

}
