//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurClassesDto
    {
        #region Constructors

        public CurClassesDto() {
        }

        public CurClassesDto(long courseId, long createby, System.DateTime createtime, System.DateTime? endDate, bool isdeleted, int? maxStudents, long? modifyby, System.DateTime? modifytime, System.DateTime? startDate, string status, long teacherId, List<CurAssignmentsDto> curAssignments, CurAttendancesDto curAttendances, CurCoursesDto curCourses, CurUsersDto curUsers, CurEnrollmentsDto curEnrollments, List<CurQuizzesDto> curQuizzes, List<CurSchedulesDto> curSchedules) {

          this.CourseId = courseId;
          this.Createby = createby;
          this.Createtime = createtime;
          this.EndDate = endDate;
          this.Isdeleted = isdeleted;
          this.MaxStudents = maxStudents;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.StartDate = startDate;
          this.Status = status;
          this.TeacherId = teacherId;
          this.CurAssignments = curAssignments;
          this.CurAttendances = curAttendances;
          this.CurCourses = curCourses;
          this.CurUsers = curUsers;
          this.CurEnrollments = curEnrollments;
          this.CurQuizzes = curQuizzes;
          this.CurSchedules = curSchedules;
        }

        #endregion

        #region Properties

        public long CourseId { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public System.DateTime? EndDate { get; set; }

        public bool Isdeleted { get; set; }

        public int? MaxStudents { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public System.DateTime? StartDate { get; set; }

        public string Status { get; set; }

        public long TeacherId { get; set; }

        #endregion

        #region Navigation Properties

        public List<CurAssignmentsDto> CurAssignments { get; set; }

        public CurAttendancesDto CurAttendances { get; set; }

        public CurCoursesDto CurCourses { get; set; }

        public CurUsersDto CurUsers { get; set; }

        public CurEnrollmentsDto CurEnrollments { get; set; }

        public List<CurQuizzesDto> CurQuizzes { get; set; }

        public List<CurSchedulesDto> CurSchedules { get; set; }

        #endregion
    }

}
