//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurCoursesDto
    {
        #region Constructors

        public CurCoursesDto() {
        }

        public CurCoursesDto(string code, long? courseTypeId, long createby, System.DateTime? createdAt, System.DateTime createtime, string description, bool isdeleted, long? modifyby, System.DateTime? modifytime, int? practicalHours, string proposal, long? qualificationId, long? specializationId, long? teachingMethodId, int? theoreticalHours, string title, List<CurClassesDto> curClasses, CurUsersDto curUsers, List<CurLrsLogsDto> curLrsLogs) {

          this.Code = code;
          this.CourseTypeId = courseTypeId;
          this.Createby = createby;
          this.CreatedAt = createdAt;
          this.Createtime = createtime;
          this.Description = description;
          this.Isdeleted = isdeleted;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.PracticalHours = practicalHours;
          this.Proposal = proposal;
          this.QualificationId = qualificationId;
          this.SpecializationId = specializationId;
          this.TeachingMethodId = teachingMethodId;
          this.TheoreticalHours = theoreticalHours;
          this.Title = title;
          this.CurClasses = curClasses;
          this.CurUsers = curUsers;
          this.CurLrsLogs = curLrsLogs;
        }

        #endregion

        #region Properties

        public string Code { get; set; }

        public long? CourseTypeId { get; set; }

        public long Createby { get; set; }

        public System.DateTime? CreatedAt { get; set; }

        public System.DateTime Createtime { get; set; }

        public string Description { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public int? PracticalHours { get; set; }

        public string Proposal { get; set; }

        public long? QualificationId { get; set; }

        public long? SpecializationId { get; set; }

        public long? TeachingMethodId { get; set; }

        public int? TheoreticalHours { get; set; }

        public string Title { get; set; }

        #endregion

        #region Navigation Properties

        public List<CurClassesDto> CurClasses { get; set; }

        public CurUsersDto CurUsers { get; set; }

        public List<CurLrsLogsDto> CurLrsLogs { get; set; }

        #endregion
    }

}
