//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurLrsLogsDto
    {
        #region Constructors

        public CurLrsLogsDto() {
        }

        public CurLrsLogsDto(string context, long? courseId, long createby, System.DateTime createtime, bool isdeleted, long? modifyby, System.DateTime? modifytime, string @object, string result, string statementId, System.DateTime? timestamp, long userId, string verb, CurUsersDto curUsers, CurCoursesDto curCourses) {

          this.Context = context;
          this.CourseId = courseId;
          this.Createby = createby;
          this.Createtime = createtime;
          this.Isdeleted = isdeleted;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.Object = @object;
          this.Result = result;
          this.StatementId = statementId;
          this.Timestamp = timestamp;
          this.UserId = userId;
          this.Verb = verb;
          this.CurUsers = curUsers;
          this.CurCourses = curCourses;
        }

        #endregion

        #region Properties

        public string Context { get; set; }

        public long? CourseId { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Object { get; set; }

        public string Result { get; set; }

        public string StatementId { get; set; }

        public System.DateTime? Timestamp { get; set; }

        public long UserId { get; set; }

        public string Verb { get; set; }

        #endregion

        #region Navigation Properties

        public CurUsersDto CurUsers { get; set; }

        public CurCoursesDto CurCourses { get; set; }

        #endregion
    }

}
