//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurOrganizationsDto
    {
        #region Constructors

        public CurOrganizationsDto() {
        }

        public CurOrganizationsDto(string code, long createby, System.DateTime? createdAt, System.DateTime createtime, bool isdeleted, int? level, long? modifyby, System.DateTime? modifytime, string name, long? parentId, string path, string type, System.DateTime? updatedAt, List<CurOrganizationsDto> curOrganizations_ParentId1, CurOrganizationsDto curOrganizations_ParentId, List<CurUsersDto> curUsers) {

          this.Code = code;
          this.Createby = createby;
          this.CreatedAt = createdAt;
          this.Createtime = createtime;
          this.Isdeleted = isdeleted;
          this.Level = level;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.Name = name;
          this.ParentId = parentId;
          this.Path = path;
          this.Type = type;
          this.UpdatedAt = updatedAt;
          this.CurOrganizations_ParentId1 = curOrganizations_ParentId1;
          this.CurOrganizations_ParentId = curOrganizations_ParentId;
          this.CurUsers = curUsers;
        }

        #endregion

        #region Properties

        public string Code { get; set; }

        public long Createby { get; set; }

        public System.DateTime? CreatedAt { get; set; }

        public System.DateTime Createtime { get; set; }

        public bool Isdeleted { get; set; }

        public int? Level { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        public long? ParentId { get; set; }

        public string Path { get; set; }

        public string Type { get; set; }

        public System.DateTime? UpdatedAt { get; set; }

        #endregion

        #region Navigation Properties

        public List<CurOrganizationsDto> CurOrganizations_ParentId1 { get; set; }

        public CurOrganizationsDto CurOrganizations_ParentId { get; set; }

        public List<CurUsersDto> CurUsers { get; set; }

        #endregion
    }

}
