//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurQuestionsDto
    {
        #region Constructors

        public CurQuestionsDto() {
        }

        public CurQuestionsDto(long createby, System.DateTime createtime, bool isdeleted, long? modifyby, System.DateTime? modifytime, long quizId, int? score, string text, string type, List<CurAnswersDto> curAnswers, List<CurQuestionAnswersDto> curQuestionAnswers, CurQuizzesDto curQuizzes) {

          this.Createby = createby;
          this.Createtime = createtime;
          this.Isdeleted = isdeleted;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.QuizId = quizId;
          this.Score = score;
          this.Text = text;
          this.Type = type;
          this.CurAnswers = curAnswers;
          this.CurQuestionAnswers = curQuestionAnswers;
          this.CurQuizzes = curQuizzes;
        }

        #endregion

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public long QuizId { get; set; }

        public int? Score { get; set; }

        public string Text { get; set; }

        public string Type { get; set; }

        #endregion

        #region Navigation Properties

        public List<CurAnswersDto> CurAnswers { get; set; }

        public List<CurQuestionAnswersDto> CurQuestionAnswers { get; set; }

        public CurQuizzesDto CurQuizzes { get; set; }

        #endregion
    }

}
