//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurQuizSubmissionsDto
    {
        #region Constructors

        public CurQuizSubmissionsDto() {
        }

        public CurQuizSubmissionsDto(long createby, System.DateTime createtime, bool isdeleted, long? modifyby, System.DateTime? modifytime, long quizId, long studentId, System.DateTime? submittedAt, decimal? totalScore, List<CurQuestionAnswersDto> curQuestionAnswers, CurQuizzesDto curQuizzes, CurUsersDto curUsers) {

          this.Createby = createby;
          this.Createtime = createtime;
          this.Isdeleted = isdeleted;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.QuizId = quizId;
          this.StudentId = studentId;
          this.SubmittedAt = submittedAt;
          this.TotalScore = totalScore;
          this.CurQuestionAnswers = curQuestionAnswers;
          this.CurQuizzes = curQuizzes;
          this.CurUsers = curUsers;
        }

        #endregion

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public long QuizId { get; set; }

        public long StudentId { get; set; }

        public System.DateTime? SubmittedAt { get; set; }

        public decimal? TotalScore { get; set; }

        #endregion

        #region Navigation Properties

        public List<CurQuestionAnswersDto> CurQuestionAnswers { get; set; }

        public CurQuizzesDto CurQuizzes { get; set; }

        public CurUsersDto CurUsers { get; set; }

        #endregion
    }

}
