//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurQuestionAnswersDto
    {
        #region Constructors

        public CurQuestionAnswersDto() {
        }

        public CurQuestionAnswersDto(string answerText, long createby, System.DateTime createtime, bool isdeleted, long? modifyby, System.DateTime? modifytime, long questionId, decimal? score, string selectedOptionIds, long submissionId, CurQuizSubmissionsDto curQuizSubmissions, CurQuestionsDto curQuestions) {

          this.AnswerText = answerText;
          this.Createby = createby;
          this.Createtime = createtime;
          this.Isdeleted = isdeleted;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.QuestionId = questionId;
          this.Score = score;
          this.SelectedOptionIds = selectedOptionIds;
          this.SubmissionId = submissionId;
          this.CurQuizSubmissions = curQuizSubmissions;
          this.CurQuestions = curQuestions;
        }

        #endregion

        #region Properties

        public string AnswerText { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public long QuestionId { get; set; }

        public decimal? Score { get; set; }

        public string SelectedOptionIds { get; set; }

        public long SubmissionId { get; set; }

        #endregion

        #region Navigation Properties

        public CurQuizSubmissionsDto CurQuizSubmissions { get; set; }

        public CurQuestionsDto CurQuestions { get; set; }

        #endregion
    }

}
