//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurQuizzesDto
    {
        #region Constructors

        public CurQuizzesDto() {
        }

        public CurQuizzesDto(long classId, long createby, System.DateTime createtime, string description, int? durationMinutes, System.DateTime? endTime, bool isdeleted, long? modifyby, System.DateTime? modifytime, System.DateTime? startTime, string title, int? totalScore, List<CurQuestionsDto> curQuestions, CurQuizSubmissionsDto curQuizSubmissions, CurClassesDto curClasses, CurUsersDto curUsers) {

          this.ClassId = classId;
          this.Createby = createby;
          this.Createtime = createtime;
          this.Description = description;
          this.DurationMinutes = durationMinutes;
          this.EndTime = endTime;
          this.Isdeleted = isdeleted;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.StartTime = startTime;
          this.Title = title;
          this.TotalScore = totalScore;
          this.CurQuestions = curQuestions;
          this.CurQuizSubmissions = curQuizSubmissions;
          this.CurClasses = curClasses;
          this.CurUsers = curUsers;
        }

        #endregion

        #region Properties

        public long ClassId { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public string Description { get; set; }

        public int? DurationMinutes { get; set; }

        public System.DateTime? EndTime { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public System.DateTime? StartTime { get; set; }

        public string Title { get; set; }

        public int? TotalScore { get; set; }

        #endregion

        #region Navigation Properties

        public List<CurQuestionsDto> CurQuestions { get; set; }

        public CurQuizSubmissionsDto CurQuizSubmissions { get; set; }

        public CurClassesDto CurClasses { get; set; }

        public CurUsersDto CurUsers { get; set; }

        #endregion
    }

}
