//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurRelatedJobsDto
    {
        #region Constructors

        public CurRelatedJobsDto() {
        }

        public CurRelatedJobsDto(int? courseId, long createby, System.DateTime createtime, bool isdeleted, long jobId, string jobTitle, long? modifyby, System.DateTime? modifytime) {

          this.CourseId = courseId;
          this.Createby = createby;
          this.Createtime = createtime;
          this.Isdeleted = isdeleted;
          this.JobId = jobId;
          this.JobTitle = jobTitle;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
        }

        #endregion

        #region Properties

        public int? CourseId { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public bool Isdeleted { get; set; }

        public long JobId { get; set; }

        public string JobTitle { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        #endregion
    }

}
