//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurTeachersDto
    {
        #region Constructors

        public CurTeachersDto() {
        }

        public CurTeachersDto(string address, System.DateTime? birthDate, string birthPlace, long createby, System.DateTime? createdAt, System.DateTime createtime, int degreeId, int? denominationId, string fatherName, int? fieldOfStudyId, string firstName, string gender, string idIssuePlace, string idNumber, bool? isAcademicMember, bool isdeleted, string lastName, int? maritalStatusId, string militaryStatus, long? modifyby, System.DateTime? modifytime, string nationalCode, string phoneLandline, string phoneMobile, string postalCode, int? religionId, int teacherTypeId, System.DateTime? updatedAt, CurReligionsDto curReligions, CurDenominationsDto curDenominations, CurMaritalStatusesDto curMaritalStatuses, CurTeacherTypesDto curTeacherTypes, CurDegreesDto curDegrees, CurFieldsOfStudyDto curFieldsOfStudy) {

          this.Address = address;
          this.BirthDate = birthDate;
          this.BirthPlace = birthPlace;
          this.Createby = createby;
          this.CreatedAt = createdAt;
          this.Createtime = createtime;
          this.DegreeId = degreeId;
          this.DenominationId = denominationId;
          this.FatherName = fatherName;
          this.FieldOfStudyId = fieldOfStudyId;
          this.FirstName = firstName;
          this.Gender = gender;
          this.IdIssuePlace = idIssuePlace;
          this.IdNumber = idNumber;
          this.IsAcademicMember = isAcademicMember;
          this.Isdeleted = isdeleted;
          this.LastName = lastName;
          this.MaritalStatusId = maritalStatusId;
          this.MilitaryStatus = militaryStatus;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.NationalCode = nationalCode;
          this.PhoneLandline = phoneLandline;
          this.PhoneMobile = phoneMobile;
          this.PostalCode = postalCode;
          this.ReligionId = religionId;
          this.TeacherTypeId = teacherTypeId;
          this.UpdatedAt = updatedAt;
          this.CurReligions = curReligions;
          this.CurDenominations = curDenominations;
          this.CurMaritalStatuses = curMaritalStatuses;
          this.CurTeacherTypes = curTeacherTypes;
          this.CurDegrees = curDegrees;
          this.CurFieldsOfStudy = curFieldsOfStudy;
        }

        #endregion

        #region Properties

        public string Address { get; set; }

        public System.DateTime? BirthDate { get; set; }

        public string BirthPlace { get; set; }

        public long Createby { get; set; }

        public System.DateTime? CreatedAt { get; set; }

        public System.DateTime Createtime { get; set; }

        public int DegreeId { get; set; }

        public int? DenominationId { get; set; }

        public string FatherName { get; set; }

        public int? FieldOfStudyId { get; set; }

        public string FirstName { get; set; }

        public string Gender { get; set; }

        public string IdIssuePlace { get; set; }

        public string IdNumber { get; set; }

        public bool? IsAcademicMember { get; set; }

        public bool Isdeleted { get; set; }

        public string LastName { get; set; }

        public int? MaritalStatusId { get; set; }

        public string MilitaryStatus { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string NationalCode { get; set; }

        public string PhoneLandline { get; set; }

        public string PhoneMobile { get; set; }

        public string PostalCode { get; set; }

        public int? ReligionId { get; set; }

        public int TeacherTypeId { get; set; }

        public System.DateTime? UpdatedAt { get; set; }

        #endregion

        #region Navigation Properties

        public CurReligionsDto CurReligions { get; set; }

        public CurDenominationsDto CurDenominations { get; set; }

        public CurMaritalStatusesDto CurMaritalStatuses { get; set; }

        public CurTeacherTypesDto CurTeacherTypes { get; set; }

        public CurDegreesDto CurDegrees { get; set; }

        public CurFieldsOfStudyDto CurFieldsOfStudy { get; set; }

        #endregion
    }

}
