//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class CurUsersDto
    {
        #region Constructors

        public CurUsersDto() {
        }

        public CurUsersDto(long createby, System.DateTime? createdAt, System.DateTime createtime, string email, string employeeNumber, string fullName, bool isdeleted, long? modifyby, System.DateTime? modifytime, string nationalCode, long? organizationId, string phone, string role, string status, System.DateTime? updatedAt, List<CurAssignmentSubmissionsDto> curAssignmentSubmissions_StudentId, List<CurAssignmentSubmissionsDto> curAssignmentSubmissions_ReviewedBy, List<CurAssignmentsDto> curAssignments, CurAttendancesDto curAttendances, List<CurClassesDto> curClasses, List<CurCoursesDto> curCourses, CurEnrollmentsDto curEnrollments, List<CurLrsLogsDto> curLrsLogs, CurQuizSubmissionsDto curQuizSubmissions, List<CurQuizzesDto> curQuizzes, CurOrganizationsDto curOrganizations) {

          this.Createby = createby;
          this.CreatedAt = createdAt;
          this.Createtime = createtime;
          this.Email = email;
          this.EmployeeNumber = employeeNumber;
          this.FullName = fullName;
          this.Isdeleted = isdeleted;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.NationalCode = nationalCode;
          this.OrganizationId = organizationId;
          this.Phone = phone;
          this.Role = role;
          this.Status = status;
          this.UpdatedAt = updatedAt;
          this.CurAssignmentSubmissions_StudentId = curAssignmentSubmissions_StudentId;
          this.CurAssignmentSubmissions_ReviewedBy = curAssignmentSubmissions_ReviewedBy;
          this.CurAssignments = curAssignments;
          this.CurAttendances = curAttendances;
          this.CurClasses = curClasses;
          this.CurCourses = curCourses;
          this.CurEnrollments = curEnrollments;
          this.CurLrsLogs = curLrsLogs;
          this.CurQuizSubmissions = curQuizSubmissions;
          this.CurQuizzes = curQuizzes;
          this.CurOrganizations = curOrganizations;
        }

        #endregion

        #region Properties

        public long Createby { get; set; }

        public System.DateTime? CreatedAt { get; set; }

        public System.DateTime Createtime { get; set; }

        public string Email { get; set; }

        public string EmployeeNumber { get; set; }

        public string FullName { get; set; }

        public bool Isdeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string NationalCode { get; set; }

        public long? OrganizationId { get; set; }

        public string Phone { get; set; }

        public string Role { get; set; }

        public string Status { get; set; }

        public System.DateTime? UpdatedAt { get; set; }

        #endregion

        #region Navigation Properties

        public List<CurAssignmentSubmissionsDto> CurAssignmentSubmissions_StudentId { get; set; }

        public List<CurAssignmentSubmissionsDto> CurAssignmentSubmissions_ReviewedBy { get; set; }

        public List<CurAssignmentsDto> CurAssignments { get; set; }

        public CurAttendancesDto CurAttendances { get; set; }

        public List<CurClassesDto> CurClasses { get; set; }

        public List<CurCoursesDto> CurCourses { get; set; }

        public CurEnrollmentsDto CurEnrollments { get; set; }

        public List<CurLrsLogsDto> CurLrsLogs { get; set; }

        public CurQuizSubmissionsDto CurQuizSubmissions { get; set; }

        public List<CurQuizzesDto> CurQuizzes { get; set; }

        public CurOrganizationsDto CurOrganizations { get; set; }

        #endregion
    }

}
