//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class SysConfigDto
    {
        #region Constructors

        public SysConfigDto() {
        }

        public SysConfigDto(long createby, System.DateTime createtime, string key, long? modifyby, System.DateTime? modifytime, string name, string remark, string value) {

          this.Createby = createby;
          this.Createtime = createtime;
          this.Key = key;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.Name = name;
          this.Remark = remark;
          this.Value = value;
        }

        #endregion

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public string Key { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        public string Remark { get; set; }

        public string Value { get; set; }

        #endregion
    }

}
