//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class SysDictionaryDataDto
    {
        #region Constructors

        public SysDictionaryDataDto() {
        }

        public SysDictionaryDataDto(long createby, System.DateTime createtime, string dictcode, string label, long modifyby, System.DateTime modifytime, int ordinal, bool status, string tagtype, string value) {

          this.Createby = createby;
          this.Createtime = createtime;
          this.Dictcode = dictcode;
          this.Label = label;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.Ordinal = ordinal;
          this.Status = status;
          this.Tagtype = tagtype;
          this.Value = value;
        }

        #endregion

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public string Dictcode { get; set; }

        public string Label { get; set; }

        public long Modifyby { get; set; }

        public System.DateTime Modifytime { get; set; }

        public int Ordinal { get; set; }

        public bool Status { get; set; }

        public string Tagtype { get; set; }

        public string Value { get; set; }

        #endregion
    }

}
