//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class SysOrganizationDto
    {
        #region Constructors

        public SysOrganizationDto() {
        }

        public SysOrganizationDto(string code, long createby, System.DateTime createtime, long modifyby, System.DateTime modifytime, string name, int ordinal, long parentid, string parentids, bool status) {

          this.Code = code;
          this.Createby = createby;
          this.Createtime = createtime;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.Name = name;
          this.Ordinal = ordinal;
          this.Parentid = parentid;
          this.Parentids = parentids;
          this.Status = status;
        }

        #endregion

        #region Properties

        public string Code { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public long Modifyby { get; set; }

        public System.DateTime Modifytime { get; set; }

        public string Name { get; set; }

        public int Ordinal { get; set; }

        public long Parentid { get; set; }

        public string Parentids { get; set; }

        public bool Status { get; set; }

        #endregion
    }

}
