//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class SysUserDto
    {
        #region Constructors

        public SysUserDto() {
        }

        public SysUserDto(string account, string avatar, System.DateTime? birthday, long createby, System.DateTime createtime, string email, string fkMenu, long fkOrganization, string fkRole, long? fkUserType, int gender, bool isConfirmed, bool isdeleted, string mobile, long modifyby, System.DateTime modifytime, string name, string nationalCode, string otpToken, System.DateTime? otpvalidto, string password, string salt, bool status, SysUserTypeDto sysUserType) {

          this.Account = account;
          this.Avatar = avatar;
          this.Birthday = birthday;
          this.Createby = createby;
          this.Createtime = createtime;
          this.Email = email;
          this.FkMenu = fkMenu;
          this.FkOrganization = fkOrganization;
          this.FkRole = fkRole;
          this.FkUserType = fkUserType;
          this.Gender = gender;
          this.IsConfirmed = isConfirmed;
          this.Isdeleted = isdeleted;
          this.Mobile = mobile;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.Name = name;
          this.NationalCode = nationalCode;
          this.OtpToken = otpToken;
          this.Otpvalidto = otpvalidto;
          this.Password = password;
          this.Salt = salt;
          this.Status = status;
          this.SysUserType = sysUserType;
        }

        #endregion

        #region Properties

        public string Account { get; set; }

        public string Avatar { get; set; }

        public System.DateTime? Birthday { get; set; }

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public string Email { get; set; }

        public string FkMenu { get; set; }

        public long FkOrganization { get; set; }

        public string FkRole { get; set; }

        public long? FkUserType { get; set; }

        public int Gender { get; set; }

        public bool IsConfirmed { get; set; }

        public bool Isdeleted { get; set; }

        public string Mobile { get; set; }

        public long Modifyby { get; set; }

        public System.DateTime Modifytime { get; set; }

        public string Name { get; set; }

        public string NationalCode { get; set; }

        public string OtpToken { get; set; }

        public System.DateTime? Otpvalidto { get; set; }

        public string Password { get; set; }

        public string Salt { get; set; }

        public bool Status { get; set; }

        #endregion

        #region Navigation Properties

        public SysUserTypeDto SysUserType { get; set; }

        #endregion
    }

}
