//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Dkd.App.Admin.Application.Dtos
{

    public partial class SysUserTypeDto
    {
        #region Constructors

        public SysUserTypeDto() {
        }

        public SysUserTypeDto(long createby, System.DateTime createtime, bool isDeleted, long? modifyby, System.DateTime? modifytime, string name, List<SysUserDto> sysUsers) {

          this.Createby = createby;
          this.Createtime = createtime;
          this.IsDeleted = isDeleted;
          this.Modifyby = modifyby;
          this.Modifytime = modifytime;
          this.Name = name;
          this.SysUsers = sysUsers;
        }

        #endregion

        #region Properties

        public long Createby { get; set; }

        public System.DateTime Createtime { get; set; }

        public bool IsDeleted { get; set; }

        public long? Modifyby { get; set; }

        public System.DateTime? Modifytime { get; set; }

        public string Name { get; set; }

        #endregion

        #region Navigation Properties

        public List<SysUserDto> SysUsers { get; set; }

        #endregion
    }

}
