using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.IdGenerators;

namespace Dkd.Infra.Repository.EfCore.MongoDB;

/// <summary>
/// An entity in a MongoDB repository.
/// </summary>
public abstract class MongoEntity : IEntity<string>
{
    /// <summary>
    /// Gets or sets the identifier.
    /// </summary>
    //_id is generated by StringObjectIdGenerator, storage type is string
    //Tell mongodb that this field's type in the database is ObjectId, this attribute is added to solve the issue when nlog generates logs and stores them as objectid type.
    [BsonId(IdGenerator = typeof(StringObjectIdGenerator))]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; } = string.Empty;
}
