//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:00:23 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class CurAssignments : EfFullAuditEntity, ICloneable {

        public CurAssignments()
        {
            this.Isdeleted = false;
            this.CurAssignmentSubmissions = new List<CurAssignmentSubmissions>();
            OnCreated();
        }

        public long ClassId { get; set; }

        public DateTime? CreatedAt { get; set; }

        public long? CreatedBy { get; set; }

        public string? Description { get; set; }

        public DateTime? DueDate { get; set; }

        public bool Isdeleted { get; set; }

        public int? MaxScore { get; set; }

        public string? Title { get; set; }

        public virtual IList<CurAssignmentSubmissions> CurAssignmentSubmissions { get; set; }

        public virtual CurClasses CurClasses { get; set; }

        public virtual CurUsers CurUsers { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CurAssignments toCompare = obj as CurAssignments;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CurAssignments obj = new CurAssignments();
            obj.ClassId = ClassId;
            obj.CreatedAt = CreatedAt;
            obj.CreatedBy = CreatedBy;
            obj.Description = Description;
            obj.DueDate = DueDate;
            obj.Isdeleted = Isdeleted;
            obj.MaxScore = MaxScore;
            obj.Title = Title;
            return obj;
        }

        #endregion
    }

}
