//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:00:23 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class CurCourses : EfFullAuditEntity, ICloneable {

        public CurCourses()
        {
            this.Isdeleted = false;
            this.CurClasses = new List<CurClasses>();
            this.CurLrsLogs = new List<CurLrsLogs>();
            OnCreated();
        }

        public string? Code { get; set; }

        public long? CourseTypeId { get; set; }

        public DateTime? CreatedAt { get; set; }

        public long? CreatedBy { get; set; }

        public string? Description { get; set; }

        public bool Isdeleted { get; set; }

        public int? PracticalHours { get; set; }

        public string? Proposal { get; set; }

        public long? QualificationId { get; set; }

        public long? SpecializationId { get; set; }

        public long? TeachingMethodId { get; set; }

        public int? TheoreticalHours { get; set; }

        public string Title { get; set; }

        public virtual IList<CurClasses> CurClasses { get; set; }

        public virtual CurUsers CurUsers { get; set; }

        public virtual IList<CurLrsLogs> CurLrsLogs { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CurCourses toCompare = obj as CurCourses;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CurCourses obj = new CurCourses();
            obj.Code = Code;
            obj.CourseTypeId = CourseTypeId;
            obj.CreatedAt = CreatedAt;
            obj.CreatedBy = CreatedBy;
            obj.Description = Description;
            obj.Isdeleted = Isdeleted;
            obj.PracticalHours = PracticalHours;
            obj.Proposal = Proposal;
            obj.QualificationId = QualificationId;
            obj.SpecializationId = SpecializationId;
            obj.TeachingMethodId = TeachingMethodId;
            obj.TheoreticalHours = TheoreticalHours;
            obj.Title = Title;
            return obj;
        }

        #endregion
    }

}
