//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:00:23 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class CurOrganizations : EfFullAuditEntity, ICloneable {

        public CurOrganizations()
        {
            this.Isdeleted = false;
            this.Level = 0;
            this.Type = @"department";
            this.CurOrganizations_ParentId1 = new List<CurOrganizations>();
            this.CurUsers = new List<CurUsers>();
            OnCreated();
        }

        public string? Code { get; set; }

        public DateTime? CreatedAt { get; set; }

        public bool Isdeleted { get; set; }

        public int? Level { get; set; }

        public string Name { get; set; }

        public long? ParentId { get; set; }

        public string? Path { get; set; }

        public string? Type { get; set; }

        public DateTime? UpdatedAt { get; set; }

        public virtual IList<CurOrganizations> CurOrganizations_ParentId1 { get; set; }

        public virtual CurOrganizations CurOrganizations_ParentId { get; set; }

        public virtual IList<CurUsers> CurUsers { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CurOrganizations toCompare = obj as CurOrganizations;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CurOrganizations obj = new CurOrganizations();
            obj.Code = Code;
            obj.CreatedAt = CreatedAt;
            obj.Isdeleted = Isdeleted;
            obj.Level = Level;
            obj.Name = Name;
            obj.ParentId = ParentId;
            obj.Path = Path;
            obj.Type = Type;
            obj.UpdatedAt = UpdatedAt;
            return obj;
        }

        #endregion
    }

}
