//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:00:23 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class CurRelatedJobs : EfFullAuditEntity, ICloneable {

        public CurRelatedJobs()
        {
            this.Isdeleted = false;
            OnCreated();
        }

        public int? CourseId { get; set; }

        public bool Isdeleted { get; set; }

        public long JobId { get; set; }

        public string? JobTitle { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CurRelatedJobs toCompare = obj as CurRelatedJobs;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.JobId, toCompare.JobId))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + JobId.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CurRelatedJobs obj = new CurRelatedJobs();
            obj.CourseId = CourseId;
            obj.Isdeleted = Isdeleted;
            obj.JobId = JobId;
            obj.JobTitle = JobTitle;
            return obj;
        }

        #endregion
    }

}
