//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:00:23 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class CurTeachers : EfFullAuditEntity, ICloneable {

        public CurTeachers()
        {
            this.IsAcademicMember = false;
            this.Isdeleted = false;
            OnCreated();
        }

        public string? Address { get; set; }

        public DateTime? BirthDate { get; set; }

        public string? BirthPlace { get; set; }

        public DateTime? CreatedAt { get; set; }

        public int DegreeId { get; set; }

        public int? DenominationId { get; set; }

        public string? FatherName { get; set; }

        public int? FieldOfStudyId { get; set; }

        public string FirstName { get; set; }

        public string Gender { get; set; }

        public string? IdIssuePlace { get; set; }

        public string? IdNumber { get; set; }

        public bool? IsAcademicMember { get; set; }

        public bool Isdeleted { get; set; }

        public string LastName { get; set; }

        public int? MaritalStatusId { get; set; }

        public string? MilitaryStatus { get; set; }

        public string NationalCode { get; set; }

        public string? PhoneLandline { get; set; }

        public string PhoneMobile { get; set; }

        public string? PostalCode { get; set; }

        public int? ReligionId { get; set; }

        public int TeacherTypeId { get; set; }

        public DateTime? UpdatedAt { get; set; }

        public virtual CurReligions CurReligions { get; set; }

        public virtual CurDenominations CurDenominations { get; set; }

        public virtual CurMaritalStatuses CurMaritalStatuses { get; set; }

        public virtual CurTeacherTypes CurTeacherTypes { get; set; }

        public virtual CurDegrees CurDegrees { get; set; }

        public virtual CurFieldsOfStudy CurFieldsOfStudy { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CurTeachers toCompare = obj as CurTeachers;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CurTeachers obj = new CurTeachers();
            obj.Address = Address;
            obj.BirthDate = BirthDate;
            obj.BirthPlace = BirthPlace;
            obj.CreatedAt = CreatedAt;
            obj.DegreeId = DegreeId;
            obj.DenominationId = DenominationId;
            obj.FatherName = FatherName;
            obj.FieldOfStudyId = FieldOfStudyId;
            obj.FirstName = FirstName;
            obj.Gender = Gender;
            obj.IdIssuePlace = IdIssuePlace;
            obj.IdNumber = IdNumber;
            obj.IsAcademicMember = IsAcademicMember;
            obj.Isdeleted = Isdeleted;
            obj.LastName = LastName;
            obj.MaritalStatusId = MaritalStatusId;
            obj.MilitaryStatus = MilitaryStatus;
            obj.NationalCode = NationalCode;
            obj.PhoneLandline = PhoneLandline;
            obj.PhoneMobile = PhoneMobile;
            obj.PostalCode = PostalCode;
            obj.ReligionId = ReligionId;
            obj.TeacherTypeId = TeacherTypeId;
            obj.UpdatedAt = UpdatedAt;
            return obj;
        }

        #endregion
    }

}
