//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:00:23 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    [Serializable()]
    public partial class CurUsers : EfFullAuditEntity, ICloneable {

        public CurUsers()
        {
            this.Isdeleted = false;
            this.Status = @"active";
            this.CurAssignmentSubmissions_StudentId = new List<CurAssignmentSubmissions>();
            this.CurAssignmentSubmissions_ReviewedBy = new List<CurAssignmentSubmissions>();
            this.CurAssignments = new List<CurAssignments>();
            this.CurClasses = new List<CurClasses>();
            this.CurCourses = new List<CurCourses>();
            this.CurLrsLogs = new List<CurLrsLogs>();
            this.CurQuizzes = new List<CurQuizzes>();
            OnCreated();
        }

        public DateTime? CreatedAt { get; set; }

        public string? Email { get; set; }

        public string? EmployeeNumber { get; set; }

        public string FullName { get; set; }

        public bool Isdeleted { get; set; }

        public string? NationalCode { get; set; }

        public long? OrganizationId { get; set; }

        public string? Phone { get; set; }

        public string Role { get; set; }

        public string? Status { get; set; }

        public DateTime? UpdatedAt { get; set; }

        public virtual IList<CurAssignmentSubmissions> CurAssignmentSubmissions_StudentId { get; set; }

        public virtual IList<CurAssignmentSubmissions> CurAssignmentSubmissions_ReviewedBy { get; set; }

        public virtual IList<CurAssignments> CurAssignments { get; set; }

        public virtual CurAttendances CurAttendances { get; set; }

        public virtual IList<CurClasses> CurClasses { get; set; }

        public virtual IList<CurCourses> CurCourses { get; set; }

        public virtual CurEnrollments CurEnrollments { get; set; }

        public virtual IList<CurLrsLogs> CurLrsLogs { get; set; }

        public virtual CurQuizSubmissions CurQuizSubmissions { get; set; }

        public virtual IList<CurQuizzes> CurQuizzes { get; set; }

        public virtual CurOrganizations CurOrganizations { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          CurUsers toCompare = obj as CurUsers;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            CurUsers obj = new CurUsers();
            obj.CreatedAt = CreatedAt;
            obj.Email = Email;
            obj.EmployeeNumber = EmployeeNumber;
            obj.FullName = FullName;
            obj.Isdeleted = Isdeleted;
            obj.NationalCode = NationalCode;
            obj.OrganizationId = OrganizationId;
            obj.Phone = Phone;
            obj.Role = Role;
            obj.Status = Status;
            obj.UpdatedAt = UpdatedAt;
            return obj;
        }

        #endregion
    }

}
