//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/5/2025 6:02:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    /// <summary>
    /// Event Tracking/Processing Information
    /// </summary>
    [Serializable()]
    public partial class SysEventtracker : EfFullAuditEntity, ICloneable {

        public SysEventtracker()
        {
            OnCreated();
        }

        public long Eventid { get; set; }

        public string Trackername { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          SysEventtracker toCompare = obj as SysEventtracker;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            SysEventtracker obj = new SysEventtracker();
            obj.Eventid = Eventid;
            obj.Trackername = Trackername;
            return obj;
        }

        #endregion
    }

}
