//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/5/2025 6:02:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Dkd.App.Admin.Repository.Entities
{
    /// <summary>
    /// Administrator
    /// </summary>
    [Serializable()]
    public partial class SysUser : EfFullAuditEntity, ICloneable {

        public SysUser()
        {
            this.Isdeleted = false;
            OnCreated();
        }

        /// <summary>
        /// Account
        /// </summary>
        public string Account { get; set; }

        /// <summary>
        /// Avatar Path
        /// </summary>
        public string Avatar { get; set; }

        /// <summary>
        /// Birthday
        /// </summary>
        public DateTime? Birthday { get; set; }

        /// <summary>
        /// Email
        /// </summary>
        public string Email { get; set; }

        public string? FkMenu { get; set; }

        /// <summary>
        /// Department ID
        /// </summary>
        public long FkOrganization { get; set; }

        public string? FkRole { get; set; }

        /// <summary>
        /// Gender
        /// </summary>
        public int Gender { get; set; }

        /// <summary>
        /// Delete Flag
        /// </summary>
        public bool Isdeleted { get; set; }

        /// <summary>
        /// Mobile Number
        /// </summary>
        public string Mobile { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Password
        /// </summary>
        public string Password { get; set; }

        /// <summary>
        /// Password Salt
        /// </summary>
        public string Salt { get; set; }

        /// <summary>
        /// Status
        /// </summary>
        public bool Status { get; set; }

        public string? OtpToken { get; set; }

        public bool IsConfirmed { get; set; }

        public DateTime? Otpvalidto { get; set; }

        public string? NationalCode { get; set; }

        public long? FkUserType { get; set; }

        public virtual SysUserType SysUserType { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          SysUser toCompare = obj as SysUser;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Id, toCompare.Id))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Id.GetHashCode();
          return hashCode;
        }

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            SysUser obj = new SysUser();
            obj.Isdeleted = Isdeleted;
            obj.Account = Account;
            obj.Avatar = Avatar;
            obj.Birthday = Birthday;
            obj.Email = Email;
            obj.Name = Name;
            obj.Password = Password;
            obj.Mobile = Mobile;
            obj.Salt = Salt;
            obj.Gender = Gender;
            obj.Status = Status;
            obj.FkRole = FkRole;
            obj.FkMenu = FkMenu;
            obj.OtpToken = OtpToken;
            obj.IsConfirmed = IsConfirmed;
            obj.Otpvalidto = Otpvalidto;
            obj.NationalCode = NationalCode;
            obj.FkUserType = FkUserType;
            return obj;
        }

        #endregion
    }

}
