//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:00:24 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurAssignmentsConfiguration in the schema.
    /// </summary>
    public class CurAssignmentsConfiguration : AbstractEntityTypeConfiguration<CurAssignments>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurAssignments> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurAssignments> builder)
        {
            base.Configure(builder);
            
            builder.Property(x => x.ClassId).HasColumnName(@"class_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"CURRENT_TIMESTAMP");
            builder.Property(x => x.CreatedBy).HasColumnName(@"created_by").HasColumnType(@"bigint").ValueGeneratedNever();
            builder.Property(x => x.Description).HasColumnName(@"description").HasColumnType(@"text").ValueGeneratedNever();
            builder.Property(x => x.DueDate).HasColumnName(@"due_date").HasColumnType(@"datetime").ValueGeneratedNever();
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.MaxScore).HasColumnName(@"max_score").HasColumnType(@"int").ValueGeneratedNever();
            builder.Property(x => x.Title).HasColumnName(@"title").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(255);
            builder.HasKey(@"Id");
            builder.HasMany(x => x.CurAssignmentSubmissions).WithOne(op => op.CurAssignments).HasForeignKey(@"AssignmentId").IsRequired(true);
            builder.HasOne(x => x.CurClasses).WithMany(op => op.CurAssignments).HasForeignKey(@"ClassId").IsRequired(true);
            builder.HasOne(x => x.CurUsers).WithMany(op => op.CurAssignments).HasForeignKey(@"CreatedBy").IsRequired(false);
        }


    }

}
