//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:00:24 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurAssignmentSubmissionsConfiguration in the schema.
    /// </summary>
    public class CurAssignmentSubmissionsConfiguration : AbstractEntityTypeConfiguration<CurAssignmentSubmissions>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurAssignmentSubmissions> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurAssignmentSubmissions> builder)
        {
            base.Configure(builder);
            
            builder.Property(x => x.AssignmentId).HasColumnName(@"assignment_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Comment).HasColumnName(@"comment").HasColumnType(@"text").ValueGeneratedNever();
            builder.Property(x => x.FileUrl).HasColumnName(@"file_url").HasColumnType(@"text").ValueGeneratedNever();
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.ReviewedAt).HasColumnName(@"reviewed_at").HasColumnType(@"datetime").ValueGeneratedNever();
            builder.Property(x => x.ReviewedBy).HasColumnName(@"reviewed_by").HasColumnType(@"bigint").ValueGeneratedNever();
            builder.Property(x => x.Score).HasColumnName(@"score").HasColumnType(@"decimal").ValueGeneratedNever().HasPrecision(5, 2);
            builder.Property(x => x.StudentId).HasColumnName(@"student_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.SubmittedAt).HasColumnName(@"submitted_at").HasColumnType(@"datetime").ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasOne(x => x.CurAssignments).WithMany(op => op.CurAssignmentSubmissions).HasForeignKey(@"AssignmentId").IsRequired(true);
            builder.HasOne(x => x.CurUsers_StudentId).WithMany(op => op.CurAssignmentSubmissions_StudentId).HasForeignKey(@"StudentId").IsRequired(true);
            builder.HasOne(x => x.CurUsers_ReviewedBy).WithMany(op => op.CurAssignmentSubmissions_ReviewedBy).HasForeignKey(@"ReviewedBy").IsRequired(false);
        }


    }

}
