//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:00:24 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurClassesConfiguration in the schema.
    /// </summary>
    public class CurClassesConfiguration : AbstractEntityTypeConfiguration<CurClasses>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurClasses> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurClasses> builder)
        {
            base.Configure(builder);
            
            builder.Property(x => x.CourseId).HasColumnName(@"course_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EndDate).HasColumnName(@"end_date").HasColumnType(@"date").ValueGeneratedNever();
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.MaxStudents).HasColumnName(@"max_students").HasColumnType(@"int").ValueGeneratedNever();
            builder.Property(x => x.StartDate).HasColumnName(@"start_date").HasColumnType(@"date").ValueGeneratedNever();
            builder.Property(x => x.Status).HasColumnName(@"status").HasColumnType(@"enum").ValueGeneratedNever().HasDefaultValueSql(@"'planned'");
            builder.Property(x => x.TeacherId).HasColumnName(@"teacher_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasMany(x => x.CurAssignments).WithOne(op => op.CurClasses).HasForeignKey(@"ClassId").IsRequired(true);
            builder.HasOne(x => x.CurAttendances).WithOne(op => op.CurClasses).HasForeignKey(typeof(CurAttendances), @"ClassId").IsRequired(false);
            builder.HasOne(x => x.CurCourses).WithMany(op => op.CurClasses).HasForeignKey(@"CourseId").IsRequired(true);
            builder.HasOne(x => x.CurUsers).WithMany(op => op.CurClasses).HasForeignKey(@"TeacherId").IsRequired(true);
            builder.HasOne(x => x.CurEnrollments).WithOne(op => op.CurClasses).HasForeignKey(typeof(CurEnrollments), @"ClassId").IsRequired(false);
            builder.HasMany(x => x.CurQuizzes).WithOne(op => op.CurClasses).HasForeignKey(@"ClassId").IsRequired(true);
            builder.HasMany(x => x.CurSchedules).WithOne(op => op.CurClasses).HasForeignKey(@"ClassId").IsRequired(true);
        }


    }

}
