//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:00:24 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurFieldsOfStudyConfiguration in the schema.
    /// </summary>
    public class CurFieldsOfStudyConfiguration : AbstractEntityTypeConfiguration<CurFieldsOfStudy>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurFieldsOfStudy> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurFieldsOfStudy> builder)
        {
            base.Configure(builder);
            
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.Name).HasColumnName(@"name").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            builder.HasKey(@"Id");
            builder.HasMany(x => x.CurTeachers).WithOne(op => op.CurFieldsOfStudy).HasForeignKey(@"FieldOfStudyId").IsRequired(false);
        }


    }

}
