//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:00:24 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurQuestionsConfiguration in the schema.
    /// </summary>
    public class CurQuestionsConfiguration : AbstractEntityTypeConfiguration<CurQuestions>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurQuestions> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurQuestions> builder)
        {
            base.Configure(builder);
            
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.QuizId).HasColumnName(@"quiz_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Score).HasColumnName(@"score").HasColumnType(@"int").ValueGeneratedNever().HasDefaultValueSql(@"1");
            builder.Property(x => x.Text).HasColumnName(@"text").HasColumnType(@"text").ValueGeneratedNever();
            builder.Property(x => x.Type).HasColumnName(@"type").HasColumnType(@"enum").IsRequired().ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasMany(x => x.CurAnswers).WithOne(op => op.CurQuestions).HasForeignKey(@"QuestionId").IsRequired(true);
            builder.HasMany(x => x.CurQuestionAnswers).WithOne(op => op.CurQuestions).HasForeignKey(@"QuestionId").IsRequired(true);
            builder.HasOne(x => x.CurQuizzes).WithMany(op => op.CurQuestions).HasForeignKey(@"QuizId").IsRequired(true);
        }


    }

}
