//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:00:24 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurQuestionAnswersConfiguration in the schema.
    /// </summary>
    public class CurQuestionAnswersConfiguration : AbstractEntityTypeConfiguration<CurQuestionAnswers>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurQuestionAnswers> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurQuestionAnswers> builder)
        {
            base.Configure(builder);
            
            builder.Property(x => x.AnswerText).HasColumnName(@"answer_text").HasColumnType(@"text").ValueGeneratedNever();
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.QuestionId).HasColumnName(@"question_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Score).HasColumnName(@"score").HasColumnType(@"decimal").ValueGeneratedNever().HasPrecision(5, 2).HasDefaultValueSql(@"0.00");
            builder.Property(x => x.SelectedOptionIds).HasColumnName(@"selected_option_ids").HasColumnType(@"text").ValueGeneratedNever();
            builder.Property(x => x.SubmissionId).HasColumnName(@"submission_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasOne(x => x.CurQuizSubmissions).WithMany(op => op.CurQuestionAnswers).HasForeignKey(@"SubmissionId").IsRequired(true);
            builder.HasOne(x => x.CurQuestions).WithMany(op => op.CurQuestionAnswers).HasForeignKey(@"QuestionId").IsRequired(true);
        }


    }

}
