//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:00:24 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurRelatedJobsConfiguration in the schema.
    /// </summary>
    public class CurRelatedJobsConfiguration : AbstractEntityTypeConfiguration<CurRelatedJobs>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurRelatedJobs> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurRelatedJobs> builder)
        {
            base.Configure(builder);
            
            builder.Property(x => x.CourseId).HasColumnName(@"course_id").HasColumnType(@"int").ValueGeneratedNever();
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.JobId).HasColumnName(@"job_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.JobTitle).HasColumnName(@"job_title").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(255);
            builder.HasKey(@"JobId");
        }


    }

}
