//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/5/2025 6:02:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for SysConfigConfiguration in the schema.
    /// </summary>
    public class SysConfigConfiguration : AbstractEntityTypeConfiguration<SysConfig>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<SysConfig> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<SysConfig> builder)
        {
            base.Configure(builder);
            builder.Property(x => x.Key).HasColumnName(@"key").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.Name).HasColumnName(@"name").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.Remark).HasColumnName(@"remark").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(128);
            builder.Property(x => x.Value).HasColumnName(@"value").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(128);
            builder.HasKey(@"Id");
        }


    }

}
