//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/5/2025 6:02:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for SysDictionaryDataConfiguration in the schema.
    /// </summary>
    public class SysDictionaryDataConfiguration : AbstractEntityTypeConfiguration<SysDictionaryData>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<SysDictionaryData> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<SysDictionaryData> builder)
        {
            base.Configure(builder);

            builder.Property(x => x.Dictcode).HasColumnName(@"dictcode").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.Label).HasColumnName(@"label").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.Ordinal).HasColumnName(@"ordinal").HasColumnType(@"int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Status).HasColumnName(@"status").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0);
            builder.Property(x => x.Tagtype).HasColumnName(@"tagtype").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.Value).HasColumnName(@"value").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.HasKey(@"Id");
        }


    }

}
