//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/5/2025 6:02:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for SysEventtrackerConfiguration in the schema.
    /// </summary>
    public class SysEventtrackerConfiguration : AbstractEntityTypeConfiguration<SysEventtracker>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<SysEventtracker> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<SysEventtracker> builder)
        {
            base.Configure(builder);

            builder.Property(x => x.Eventid).HasColumnName(@"eventid").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Trackername).HasColumnName(@"trackername").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            builder.HasKey(@"Id");
            builder.HasIndex(@"Eventid", @"Trackername").IsUnique(true).HasDatabaseName(@"ix_sys_eventtracker_eventid_trackername");
        }


    }

}
