//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 6/5/2025 6:02:22 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for SysMenuConfiguration in the schema.
    /// </summary>
    public class SysMenuConfiguration : AbstractEntityTypeConfiguration<SysMenu>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<SysMenu> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<SysMenu> builder)
        {
            base.Configure(builder);
            builder.Property(x => x.Alwaysshow).HasColumnName(@"alwaysshow").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0);
            builder.Property(x => x.Component).HasColumnName(@"component").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.Icon).HasColumnName(@"icon").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.Keepalive).HasColumnName(@"keepalive").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0);
            builder.Property(x => x.Name).HasColumnName(@"name").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.Ordinal).HasColumnName(@"ordinal").HasColumnType(@"int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Params).HasColumnName(@"params").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(128);
            builder.Property(x => x.Parentid).HasColumnName(@"parentid").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Parentids).HasColumnName(@"parentids").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(128);
            builder.Property(x => x.Perm).HasColumnName(@"perm").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(32);
            builder.Property(x => x.Redirect).HasColumnName(@"redirect").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(128);
            builder.Property(x => x.Routename).HasColumnName(@"routename").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.Routepath).HasColumnName(@"routepath").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(64);
            builder.Property(x => x.Type).HasColumnName(@"type").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(16);
            builder.Property(x => x.Visible).HasColumnName(@"visible").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0);
            builder.HasKey(@"Id");
        }


    }

}
