//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurAttendancesConfiguration in the schema.
    /// </summary>
    public class CurAttendancesConfiguration : AbstractEntityTypeConfiguration<CurAttendances>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurAttendances> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurAttendances> builder)
        {
            base.Configure(builder);
            builder.ToTable(@"cur_attendances", SchemaNames.DefaultEntities);
            builder.Property(x => x.ClassId).HasColumnName(@"class_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"CURRENT_TIMESTAMP");
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.SessionDate).HasColumnName(@"session_date").HasColumnType(@"date").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Status).HasColumnName(@"status").HasColumnType(@"enum").ValueGeneratedNever().HasDefaultValueSql(@"'present'");
            builder.Property(x => x.StudentId).HasColumnName(@"student_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.UpdatedAt).HasColumnName(@"updated_at").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"CURRENT_TIMESTAMP");
            builder.HasKey(@"Id");
            builder.HasIndex(@"ClassId", @"SessionDate", @"StudentId").IsUnique(true).HasDatabaseName(@"class_id");
        }


    }

}
