//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurCourseContentsConfiguration in the schema.
    /// </summary>
    public class CurCourseContentsConfiguration : AbstractEntityTypeConfiguration<CurCourseContents>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurCourseContents> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurCourseContents> builder)
        {
            base.Configure(builder);
            builder.ToTable(@"cur_course_contents", SchemaNames.DefaultEntities);
            builder.Property(x => x.ContentDescription).HasColumnName(@"content_description").HasColumnType(@"text").ValueGeneratedNever();
            builder.Property(x => x.CourseId).HasColumnName(@"course_id").HasColumnType(@"int").ValueGeneratedNever();
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.HasKey(@"Id");
        }


    }

}
