//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurEnrollmentsConfiguration in the schema.
    /// </summary>
    public class CurEnrollmentsConfiguration : AbstractEntityTypeConfiguration<CurEnrollments>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurEnrollments> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurEnrollments> builder)
        {
            base.Configure(builder);
            builder.ToTable(@"cur_enrollments", SchemaNames.DefaultEntities);
            builder.Property(x => x.ClassId).HasColumnName(@"class_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EnrolledAt).HasColumnName(@"enrolled_at").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"CURRENT_TIMESTAMP");
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.Status).HasColumnName(@"status").HasColumnType(@"enum").ValueGeneratedNever().HasDefaultValueSql(@"'active'");
            builder.Property(x => x.StudentId).HasColumnName(@"student_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasIndex(@"ClassId", @"StudentId").IsUnique(true).HasDatabaseName(@"class_id");
        }


    }

}
