//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurLrsLogsConfiguration in the schema.
    /// </summary>
    public class CurLrsLogsConfiguration : AbstractEntityTypeConfiguration<CurLrsLogs>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurLrsLogs> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurLrsLogs> builder)
        {
            base.Configure(builder);
            builder.ToTable(@"cur_lrs_logs", SchemaNames.DefaultEntities);
            builder.Property(x => x.Context).HasColumnName(@"context").HasColumnType(@"json").ValueGeneratedNever();
            builder.Property(x => x.CourseId).HasColumnName(@"course_id").HasColumnType(@"bigint").ValueGeneratedNever();
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.Object).HasColumnName(@"object").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(1000);
            builder.Property(x => x.Result).HasColumnName(@"result").HasColumnType(@"json").ValueGeneratedNever();
            builder.Property(x => x.StatementId).HasColumnName(@"statement_id").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(100);
            builder.Property(x => x.Timestamp).HasColumnName(@"timestamp").HasColumnType(@"datetime").ValueGeneratedNever();
            builder.Property(x => x.UserId).HasColumnName(@"user_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Verb).HasColumnName(@"verb").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(100);
            builder.HasKey(@"Id");
            builder.HasOne(x => x.CurUsers).WithMany(op => op.CurLrsLogs).HasForeignKey(@"UserId").IsRequired(true);
            builder.HasOne(x => x.CurCourses).WithMany(op => op.CurLrsLogs).HasForeignKey(@"CourseId").IsRequired(false);
        }


    }

}
