//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurOrganizationsConfiguration in the schema.
    /// </summary>
    public class CurOrganizationsConfiguration : AbstractEntityTypeConfiguration<CurOrganizations>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurOrganizations> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurOrganizations> builder)
        {
            base.Configure(builder);
            builder.ToTable(@"cur_organizations", SchemaNames.DefaultEntities);
            builder.Property(x => x.Code).HasColumnName(@"code").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(50);
            builder.Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"CURRENT_TIMESTAMP");
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.Level).HasColumnName(@"level").HasColumnType(@"int").ValueGeneratedNever().HasDefaultValueSql(@"0");
            builder.Property(x => x.Name).HasColumnName(@"name").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(255);
            builder.Property(x => x.ParentId).HasColumnName(@"parent_id").HasColumnType(@"bigint").ValueGeneratedNever();
            builder.Property(x => x.Path).HasColumnName(@"path").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(1000);
            builder.Property(x => x.Type).HasColumnName(@"type").HasColumnType(@"enum").ValueGeneratedNever().HasDefaultValueSql(@"'department'");
            builder.Property(x => x.UpdatedAt).HasColumnName(@"updated_at").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"CURRENT_TIMESTAMP");
            builder.HasKey(@"Id");
            builder.HasIndex(@"Code").IsUnique(true);
            builder.HasMany(x => x.CurOrganizations_ParentId1).WithOne(op => op.CurOrganizations_ParentId).HasForeignKey(@"ParentId").IsRequired(false);
            builder.HasOne(x => x.CurOrganizations_ParentId).WithMany(op => op.CurOrganizations_ParentId1).HasForeignKey(@"ParentId").IsRequired(false);
            builder.HasMany(x => x.CurUsers).WithOne(op => op.CurOrganizations).HasForeignKey(@"OrganizationId").IsRequired(false);
        }


    }

}
