//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurQuizzesConfiguration in the schema.
    /// </summary>
    public class CurQuizzesConfiguration : AbstractEntityTypeConfiguration<CurQuizzes>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurQuizzes> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurQuizzes> builder)
        {
            base.Configure(builder);
            builder.ToTable(@"cur_quizzes", SchemaNames.DefaultEntities);
            builder.Property(x => x.ClassId).HasColumnName(@"class_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.CreatedBy).HasColumnName(@"created_by").HasColumnType(@"bigint").ValueGeneratedNever();
            builder.Property(x => x.Description).HasColumnName(@"description").HasColumnType(@"text").ValueGeneratedNever();
            builder.Property(x => x.DurationMinutes).HasColumnName(@"duration_minutes").HasColumnType(@"int").ValueGeneratedNever();
            builder.Property(x => x.EndTime).HasColumnName(@"end_time").HasColumnType(@"datetime").ValueGeneratedNever();
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.StartTime).HasColumnName(@"start_time").HasColumnType(@"datetime").ValueGeneratedNever();
            builder.Property(x => x.Title).HasColumnName(@"title").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(255);
            builder.Property(x => x.TotalScore).HasColumnName(@"total_score").HasColumnType(@"int").ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasMany(x => x.CurQuestions).WithOne(op => op.CurQuizzes).HasForeignKey(@"QuizId").IsRequired(true);
            builder.HasOne(x => x.CurQuizSubmissions).WithOne(op => op.CurQuizzes).HasForeignKey(typeof(CurQuizSubmissions), @"QuizId").IsRequired(false);
            builder.HasOne(x => x.CurClasses).WithMany(op => op.CurQuizzes).HasForeignKey(@"ClassId").IsRequired(true);
            builder.HasOne(x => x.CurUsers).WithMany(op => op.CurQuizzes).HasForeignKey(@"CreatedBy").IsRequired(false);
        }


    }

}
