//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurQuizSubmissionsConfiguration in the schema.
    /// </summary>
    public class CurQuizSubmissionsConfiguration : AbstractEntityTypeConfiguration<CurQuizSubmissions>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurQuizSubmissions> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurQuizSubmissions> builder)
        {
            base.Configure(builder);
            builder.ToTable(@"cur_quiz_submissions", SchemaNames.DefaultEntities);
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.QuizId).HasColumnName(@"quiz_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.StudentId).HasColumnName(@"student_id").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.SubmittedAt).HasColumnName(@"submitted_at").HasColumnType(@"datetime").ValueGeneratedNever();
            builder.Property(x => x.TotalScore).HasColumnName(@"total_score").HasColumnType(@"decimal").ValueGeneratedNever().HasPrecision(5, 2);
            builder.HasKey(@"Id");
            builder.HasIndex(@"QuizId", @"StudentId").IsUnique(true).HasDatabaseName(@"quiz_id");
            builder.HasMany(x => x.CurQuestionAnswers).WithOne(op => op.CurQuizSubmissions).HasForeignKey(@"SubmissionId").IsRequired(true);
        }


    }

}
