//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for CurTeachersConfiguration in the schema.
    /// </summary>
    public class CurTeachersConfiguration : AbstractEntityTypeConfiguration<CurTeachers>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CurTeachers> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<CurTeachers> builder)
        {
            base.Configure(builder);
            builder.ToTable(@"cur_teachers", SchemaNames.DefaultEntities);
            builder.Property(x => x.Address).HasColumnName(@"address").HasColumnType(@"text").ValueGeneratedNever();
            builder.Property(x => x.BirthDate).HasColumnName(@"birth_date").HasColumnType(@"date").ValueGeneratedNever();
            builder.Property(x => x.BirthPlace).HasColumnName(@"birth_place").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(100);
            builder.Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"CURRENT_TIMESTAMP");
            builder.Property(x => x.DegreeId).HasColumnName(@"degree_id").HasColumnType(@"int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DenominationId).HasColumnName(@"denomination_id").HasColumnType(@"int").ValueGeneratedNever();
            builder.Property(x => x.FatherName).HasColumnName(@"father_name").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(100);
            builder.Property(x => x.FieldOfStudyId).HasColumnName(@"field_of_study_id").HasColumnType(@"int").ValueGeneratedNever();
            builder.Property(x => x.FirstName).HasColumnName(@"first_name").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            builder.Property(x => x.Gender).HasColumnName(@"gender").HasColumnType(@"enum").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IdIssuePlace).HasColumnName(@"id_issue_place").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(100);
            builder.Property(x => x.IdNumber).HasColumnName(@"id_number").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(20);
            builder.Property(x => x.IsAcademicMember).HasColumnName(@"is_academic_member").HasColumnType(@"tinyint").ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.Isdeleted).HasColumnName(@"isdeleted").HasColumnType(@"tinyint").IsRequired().ValueGeneratedNever().HasPrecision(1, 0).HasDefaultValueSql(@"0");
            builder.Property(x => x.LastName).HasColumnName(@"last_name").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            builder.Property(x => x.MaritalStatusId).HasColumnName(@"marital_status_id").HasColumnType(@"int").ValueGeneratedNever();
            builder.Property(x => x.MilitaryStatus).HasColumnName(@"military_status").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(50);
            builder.Property(x => x.NationalCode).HasColumnName(@"national_code").HasColumnType(@"char").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            builder.Property(x => x.PhoneLandline).HasColumnName(@"phone_landline").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(15);
            builder.Property(x => x.PhoneMobile).HasColumnName(@"phone_mobile").HasColumnType(@"varchar").IsRequired().ValueGeneratedNever().HasMaxLength(15);
            builder.Property(x => x.PostalCode).HasColumnName(@"postal_code").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(20);
            builder.Property(x => x.ReligionId).HasColumnName(@"religion_id").HasColumnType(@"int").ValueGeneratedNever();
            builder.Property(x => x.TeacherTypeId).HasColumnName(@"teacher_type_id").HasColumnType(@"int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.UpdatedAt).HasColumnName(@"updated_at").HasColumnType(@"datetime").ValueGeneratedOnAdd().HasDefaultValueSql(@"CURRENT_TIMESTAMP");
            builder.HasKey(@"Id");
            builder.HasIndex(@"NationalCode").IsUnique(true);
            builder.HasOne(x => x.CurReligions).WithMany(op => op.CurTeachers).HasForeignKey(@"ReligionId").IsRequired(false);
            builder.HasOne(x => x.CurDenominations).WithMany(op => op.CurTeachers).HasForeignKey(@"DenominationId").IsRequired(false);
            builder.HasOne(x => x.CurMaritalStatuses).WithMany(op => op.CurTeachers).HasForeignKey(@"MaritalStatusId").IsRequired(false);
            builder.HasOne(x => x.CurTeacherTypes).WithMany(op => op.CurTeachers).HasForeignKey(@"TeacherTypeId").IsRequired(true);
            builder.HasOne(x => x.CurDegrees).WithMany(op => op.CurTeachers).HasForeignKey(@"DegreeId").IsRequired(true);
            builder.HasOne(x => x.CurFieldsOfStudy).WithMany(op => op.CurTeachers).HasForeignKey(@"FieldOfStudyId").IsRequired(false);
        }


    }

}
