//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for SysRoleMenuRelationConfiguration in the schema.
    /// </summary>
    public class SysRoleMenuRelationConfiguration : AbstractEntityTypeConfiguration<SysRoleMenuRelation>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<SysRoleMenuRelation> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<SysRoleMenuRelation> builder)
        {
            base.Configure(builder);
            builder.ToTable(@"sys_role_menu_relation", SchemaNames.DefaultEntities);
            builder.Property(x => x.Menuid).HasColumnName(@"menuid").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Roleid).HasColumnName(@"roleid").HasColumnType(@"bigint").IsRequired().ValueGeneratedNever();
            builder.HasKey(@"Id");
        }


    }

}
