//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/3/2025 12:38:38 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dkd.App.Planingschedule.Repository.Entities.Config
{
    /// <summary>
    /// There are no comments for SysUserTypeConfiguration in the schema.
    /// </summary>
    public class SysUserTypeConfiguration : AbstractEntityTypeConfiguration<SysUserType>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<SysUserType> builder) method in the schema.
        /// </summary>
        public override void Configure(EntityTypeBuilder<SysUserType> builder)
        {
            base.Configure(builder);
            builder.ToTable(@"sys_UserType", SchemaNames.DefaultEntities);
            builder.Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType(@"bit").IsRequired().ValueGeneratedNever().HasPrecision(1).HasDefaultValueSql(@"b'0'");
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType(@"varchar").ValueGeneratedNever().HasMaxLength(50);
            builder.HasKey(@"Id");
            builder.HasMany(x => x.SysUsers).WithOne(op => op.SysUserType).HasForeignKey(@"FkUserType").IsRequired(false);
        }


    }

}
